- src/Cedar/Virtual.c
Suppose there is a TCP SYN or SYN-ACK packet taking options as:
02 04 05 b4 01 01 04 02 01 03 03 04 
which is 
Options: (12 bytes)
>Maximum segment size: 1460 bytes
>No-Operation (NOP)
>No-Operation (NOP)
>TCP SACK Permitted Option: True
>No-Operation (NOP)
>Window scale: 4 (multiply by 16)
Then the original parse function only returns MSS 1460 while WSS is 0.
> Fix that ParseTcpOption doesn't work correctly

- debian/softether-vpnserver.init
Latest Debian's init script requires LSB header, at least Jessie requires this.
> Add LSB header

- debian/rules
It now does not build as `debian/rules` does not launch the `configure` script. This should fix that.
> Support Debian package build on ARMv7l architecture

- src/Cedar/Admin.c
- src/Cedar/Client.c
- src/Cedar/Connection.c
- src/Cedar/SM.c
- src/Cedar/UdpAccel.c
- src/Cedar/Virtual.c
- src/Cedar/WebUI.c
- src/Mayaqua/FileIO.c
- src/Mayaqua/TcpIp.c
[src/Cedar/Admin.c:11843] -> [src/Cedar/Admin.c:11845]: (warning) Either the condition 't==0' is redundant or there is possible null pointer dereference: t.
[src/Cedar/Admin.c:12316] -> [src/Cedar/Admin.c:12318]: (warning) Either the condition 'a==0' is redundant or there is possible null pointer dereference: a.
[src/Cedar/Admin.c:12576] -> [src/Cedar/Admin.c:12578]: (warning) Either the condition 't==0' is redundant or there is possible null pointer dereference: t.
[src/Cedar/Admin.c:12790] -> [src/Cedar/Admin.c:12792]: (warning) Either the condition 't==0' is redundant or there is possible null pointer dereference: t.
> cppcheck issues

- src/Cedar/Server.c
Due to DROWN (CVE-2016-0800), SSLv2 must be disabled by default. This is the most straight-forward way to ensure new installations are not vulnerable. The upgrade use case is not addressed by this PR, though I posted information to the forum: http://www.vpnusers.com/viewtopic.php?f=7&t=5596
This patch is made available under Contribution Option 1, to allow PacketiX to be fixed the same way.
> Default to TLS connections only

- src/Cedar/Cedar.c
- src/Cedar/Cedar.h
- src/Cedar/Connection.c
- src/Cedar/Server.c
- src/Mayaqua/Network.c
- src/Mayaqua/Network.h
Here is a patch to disable a specific SSL/TLS version to be used on server. The AcceptOnlyTls setting had also been changed to use the same mechanism to disable SSL versions 2 and 3.
> Allow specific SSL/TLS versions to be disabled

- src/Mayaqua/Network.c
Current kevent() implementation in SoftEther is broken.  It always exits with -1.
This causes 100% CPU utilization during connected session.
Attached select() implementation of the same functionality.
Now the CPU usage is normal.
Please use (Contribution option (1))
> Fixed OSX CPU utilization by replacing broken kevent() with select()

- debian/rules
- src/Cedar/Interop_OpenVPN.c
Armv5tel is for building Debian package on SheevaPlug.
Also, static routes not working properly with OpenVPN as gateway address gets replaced by vpn_gateway. So, you cannot direct all traffic to VPN and make some nets to go through net_gateway.
By the way, even with this fix you have to specify IP address as gateway in config file and cannot use openvpn's vpn_gateway and net_gateway keywords.
> Added armv5tel for debian/rules and made pushed routes work correct with OpenVPN

- src/Cedar/Command.c
["LogFileGet": ログファイルのダウンロード](https://ja.softether.org/4-docs/1-manual/6/6.3#6.3.56_.22LogFileGet.22:_.E3.83.AD.E3.82.B0.E3.83.95.E3.82.A1.E3.82.A4.E3.83.AB.E3.81.AE.E3.83.80.E3.82.A6.E3.83.B3.E3.83.AD.E3.83.BC.E3.83.89) にある`/SAVEPATH` パラメータがうまく動いていないのを修正
ref http://www.vpnusers.com/viewtopic.php?t=2750
> fix LogFileGet won't save to SAVEPATH

- debian/rules
Fixing error for Debian GNU/Linux 7 
During install launching: $ debuild binary 
Select your operating system below:
1: Linux
2: FreeBSD
3: Solaris
4: Mac OS X
5: OpenBSD
Which is your operating system (1 - 5) ? : 
Wrong number.
make[1]: **\* [configure_config] Error 1
make[1]: Leaving directory `/usr/local/src/SoftEtherVPN'
make: **\* [binary] Error 2
debuild: fatal error at line 1333:
couldn't exec debian/rules:
> Fix for Debian Package

- configure
This tries to autodetect the OS and CPU instead of unconditionally requiring user input -- and falls back to the user prompts if autodetection didn't work
> Try to autodetect OS and CPU instead of requiring user input

- src/Cedar/Hub.h
- src/Cedar/Sam.c
- src/Cedar/Server.c
This adds the ability to specify (in the configuration file) a realm to be used for Radius authentication.  Realms are specified on a per-Hub basis.
> Support For Radius Realm

- src/Cedar/Client.c
- src/Cedar/Interop_OpenVPN.c
Using the global client variable might lead to strange behavoir if multiple clients are allocated and to crashes in the case the client was not initialized with CtStartClient()
> Using client parameter in function CtConnect

- debian/softether-vpnserver.init
There was a blank line at the start of the file before #! /bin/sh, which declares which interpeter it has to use. With this blank line the init script will not work and will throw error "exit status 1", meaning the deamon doesn't start.
The change was introduced in version 4.22.
This simple edit to the file will fix that.
> Remove blank line at the start from init file (Debian)

- src/Cedar/IPsec_PPP.c
Hi, 
I have found a bug in the IPSec_PPP module, where the packet re-transmission timer is still counting while it is waiting on the radius server. 
This causes the MSCHAP start packet to be sent twice, even after authentication has successfully concluded. As it has moved on to IPCP, when the reply comes in from the client, the session is terminated and the connection fails. Therefore, if the radius AUTH takes longer than 1000ms, SSTP/IPsec (PPP-based protocols) fail.
My solution to this is to backup the timer values when a request is received.
I choose Contribution option (1)
Thanks,
Noah
> Stop Radius Delay from counting to next_resend

- src/Cedar/IPsec_IkePacket.c
- src/Cedar/IPsec_IkePacket.h
Added definition for the DH groups 2048,3072,4096.
This is necessary to implement IPSec tunneling as well as IKEv2
I used the names: group2048 instead of group14 add analog for other names. The same has been done by dnobori in commit 4df2eb4
> Add DH groups 2048,3072,4096 to IPSec_IKE

- src/Mayaqua/Encrypt.c
I try to import few Trusted CA certificates and some of it gave error. After i'm go through the code and found wrong calculation RSA bits in file Mayaqua/encrypt.c in function X *X509ToX(X509 *x509). This patch I'm already make little changes to solved it. Below sample Trusted certificate have result error for u to test. This certificate own by one of the trusted CA in our country. Hope the patch can help other people have same issue with me.
-----BEGIN CERTIFICATE-----
MIIFWDCCBECgAwIBAgIBBDANBgkqhkiG9w0BAQsFADB/MQswCQYDVQQGEwJteTEL
MAkGA1UECgwCVE0xNDAyBgNVBAsMK1RNIEFwcGxpZWQgQnVzaW5lc3MgQ2VydGlm
aWNhdGlvbiBBdXRob3JpdHkxLTArBgNVBAMMJFRNIEFwcGxpZWQgQnVzaW5lc3Mg
Um9vdCBDZXJ0aWZpY2F0ZTAeFw0xMTEwMTAwODEzMjdaFw0zMDEwMTAwODQzMjda
MF8xCzAJBgNVBAYTAm15MQswCQYDVQQKDAJUTTENMAsGA1UECwwEVE1DQTE0MDIG …
> Fixed RSA key bits wrong calculation for certain x509 certificate

- src/Mayaqua/Encrypt.c
- src/Mayaqua/Encrypt.h
- src/Mayaqua/Network.c
- src/Mayaqua/Secure.c
- Changed Mayaqua to be compilable against OpenSSL 1.1.x.
- Some potentially sketchy change regarding `Ssl_Init_Async_SendAlert` that I'd feel much better about if someone can tell me what it actually does.
Option 1 chosen.
> OpenSSL 1.1 Port

- .gitignore
- Adds initial .gitignore file
- This files ignores known files by different IDEs like eclipse and intellij as well as files generated by SE Compilation like tmp/ and hamcore files
- 
- Option 1
> Initial Commit of gitignore

- src/makefiles/linux_64bit.mak
This patch fixes an error when trying to build under the `aarch64` because the compiler there does not know the option `-m64` and fails when gets it.
Below is attached a part of relevant build log:
```
if [ aarch64 = 'aarch64' ]; then echo -e "1\n2\n" | ./configure; fi
---------------------------------------------------------------------
SoftEther VPN for Unix
Copyright (c) SoftEther VPN Project at University of Tsukuba, Japan.
Copyright (c) Daiyuu Nobori. All Rights Reserved.
This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
version 2 as published by the Free Software Foundation.
Read and understand README.TXT, LICENSE.TXT and WARNING.TXT before use.
-------------------------------------------------------------------- …
```
> fix aarch64 build

- AUTHORS.TXT
- src/Cedar/IPsec_L2TP.c
- src/Cedar/IPsec_PPP.c
- src/Cedar/Interop_OpenVPN.c
- src/Cedar/Radius.c
- src/Cedar/Virtual.c
- src/Mayaqua/Memory.c
- src/Mayaqua/Memory.h
- src/Mayaqua/Network.c
- src/Mayaqua/Pack.c
- src/Mayaqua/Str.c
- src/Mayaqua/Str.h
- src/Mayaqua/TcpIp.c
- src/bin/hamcore/authors.txt
There are 11 vulnerabilities on SoftEther VPN. There vulnerabilities are found by the source code audit process conducted by Max Planck Institute for Molecular Genetics and Mr. Guido Vranken in late 2017. This patch fixes all of these vulnerabilities.
7 missing memory boundaries checks and similar memory problems. There are no risk of arbitrary code execution or intrusion on these bugs in my analysis. However, these problems may lead to crash the running server process. So these bugs must be fixed.
- Buffer overread in ParseL2TPPacket()
- Memory corruption in IcmpParseResult
- Missing bounds check in ParseUDP() can lead to invalid memory access
- Out-of-bounds read in IPsec_PPP.c (unterminated string buffer)
- Overlapping parameters to memcpy() via StrToIp6()
- PACK ReadValue() crash …
> Fixes 11 vulnerabilities found by Max Planck Institute for Molecular Genetics and Mr. Guido Vranken

- src/Mayaqua/Win32.c
Fix a bug in the Win32EnumDirExW() function, where the wrong variable was being used.
> Fix a bug in the Win32EnumDirExW() function.

- README.md
- Corrected package name for OpenSSL dependency
Option 1
-
> Changed OpenSSL package name

- .travis.yml
- debian/control
debian: fix dependencies
- it should fix armh build failures reported by @paskal
- 1
> travis-ci: add "dh build-arch" step, fix debian packaging

- src/Cedar/Cedar.h
- src/Cedar/IPsec_EtherIP.c
- src/Cedar/IPsec_IPC.c
- src/Cedar/IPsec_IPC.h
- src/Cedar/IPsec_PPP.c
- src/Cedar/Interop_OpenVPN.c
- src/Cedar/Interop_OpenVPN.h
- src/Cedar/Protocol.c
- src/Cedar/Protocol.h
- src/Mayaqua/Encrypt.c
- src/Mayaqua/Encrypt.h
- src/Mayaqua/Network.c
- src/Mayaqua/Network.h
- src/bin/hamcore/strtable_cn.stb
- src/bin/hamcore/strtable_en.stb
- src/bin/hamcore/strtable_ja.stb
- src/bin/hamcore/strtable_tw.stb
This pull request implements Individual Certificate Authentication for OpenVPN protocol. This pull request fixes #55.
Client certificate's _Common Name_ is used as username during authentication process. If ``auth-user-pass`` is enabled for OpenVPN client, the password is ignored by server, and username recieved from the client is used instead of the Common Name.
*Note*: only self-signed certificates work presently. CA-signed certificates will not pass verification because OpenSSL library needs to be told where to look for trusted CA certificates, and this feature was not implemented in this pull request. It can be easily added in future, though.
--------
Example:
1. Connect to SoftEther Server via command line client.
2. Create a new user, let's name him **steve**:
```
VPN …
```
> OpenVPN client certificate authentication (Individual Certificate Authentication)

- .ci/build-openssl.sh
- .travis.yml
- src/makefiles/linux_32bit.mak
- src/makefiles/linux_64bit.mak
- introducing openssl-1.1.0 in travis-ci builds
- one
> travis-ci: split openssl into 1.0.2, 1.1.0 matrix

- src/Cedar/Admin.c
- src/Cedar/Hub.c
- src/Cedar/Protocol.c
- src/Cedar/SM.c
[src/Cedar/Admin.c:13452] -> [src/Cedar/Admin.c:13492]: (warning) Either the condition 'cedar!=NULL' is redundant or there is possible null pointer dereference: cedar.
[src/Cedar/SM.c:18455] -> [src/Cedar/SM.c:18379]: (warning) Either the condition 'p!=NULL' is redundant or there is possible null pointer dereference: p.
[src/Cedar/SM.c:18455] -> [src/Cedar/SM.c:18491]: (warning) Either the condition 'p!=NULL' is redundant or there is possible null pointer dereference: p.
[src/Cedar/SM.c:18455] -> [src/Cedar/SM.c:18506]: (warning) Either the condition 'p!=NULL' is redundant or there is possible null pointer dereference: p.
[src/Cedar/Protocol.c:5190] -> [src/Cedar/Protocol.c:5115]: (warning) Either the condition 's!=NULL' is redundant or there is possible null pointer dereference: s. …
> resolve several issues identified by cppcheck

- src/Cedar/Admin.c
- src/Cedar/Server.c
Because `sizeof(t) == sizeof(void *)` and Zero() clears only first 4/8 bytes of struct.
> Use correct sizeof value

- src/Cedar/Logging.c
- src/Cedar/WebUI.c
- src/Mayaqua/Cfg.c
Bug reported by the clang static analyzer.
Description: Call to function 'strcpy' is insecure as it does not provide bounding of the memory buffer. Replace unbounded copy functions with analogous functions that support length arguments such as 'strlcpy'. CWE-119
File: /home/tc/git/softetherVPN/src/Cedar/Logging.c
Line: 2409
Description: The left operand of '==' is a garbage value
File: /home/tc/git/softetherVPN/src/Cedar/WebUI.c
Line: 369
Description: Access to field 'p' results in a dereference of a null pointer (loaded from field 'Items')
File: /home/tc/git/softetherVPN/src/Mayaqua/Cfg.c
Line: 2257
> initial fix for clang warnings

- .appveyor.yml
This is required because we are currently using `build-{build}-{commit-sha1}` as build name pattern.
There may be multiple builds for the same commit.
---
> AppVeyor: increment build number with pull requests, in order to avoid conflicts

- src/Cedar/Sam.c
- src/Mayaqua/MayaType.h
User can authenticate against Windows AD Server from Linux VPN SoftEther Server. 
- the linux server is member of the domain
- the authentication takes place due to ntlm_auth
- if the groupname is set in u->GroupName (VPN UserManagement) it will represent the AD Group and is required
tested on centos 2.6.32-431.11.2.el6.x86_64
a timeout for auth_ntlm should be implemented in production release
> SMB Winbind NT Authentication (Password/MsCHAPv2)

- src/Cedar/Interop_OpenVPN.c
- Some OpenVPN clients (MikroTik router for example) do not send the peer info along with the key exchange. This patch makes the peer info string optional on the SoftEtherVPN side.
- I choose option 1
> Peer info optional in OvsParseKeyMethod2()

- src/Cedar/Connection.c
- src/Cedar/Protocol.c
[src/Cedar/Connection.c:1090] -> [src/Cedar/Connection.c:1086]:
(warning) Either the condition 's!=NULL' is redundant or there is possible null pointer dereference: s.
macros IS_SEND_TCP_SOCK expands into "s" dereferencing, so check for NULL should go before that macros
[src/Cedar/Protocol.c:2951] -> [src/Cedar/Protocol.c:2892]:
(warning) Either the condition 'policy!=NULL' is redundant or there is possible null pointer dereference: policy.
[src/Cedar/Protocol.c:2951] -> [src/Cedar/Protocol.c:2901]:
(warning) Either the condition 'policy!=NULL' is redundant or there is possible null pointer dereference: policy.
[src/Cedar/Protocol.c:3151] -> [src/Cedar/Protocol.c:3082]:
(warning) Either the condition 'policy!=NULL' is redundant or there is possible null pointer dereference: policy. …
> resolve several issues found by cppcheck

- src/Cedar/Command.c
- src/bin/hamcore/strtable_en.stb
This is allows to change "Disable UDP acceleration" via vpncmd. #308 
1
> [vpncmd] Added DISABLEUDP option into AccountDetailSet command.

- src/Cedar/Client.c
- src/Cedar/Virtual.c
- src/Mayaqua/Microsoft.c
- Improving the compliance of Virtual Network Adapters with the local address bit of the MAC address rule.
- When installing a new device driver of the Virtual Network Driver card, we changed the initial random MAC address from 00-AC-xx-xx-xx-xx to 5E-xx-xx-xx-xx-xx. This realizes the compliance with the local address bit of the MAC address rule.
- 1
> Improving the compliance of Virtual Network Adapters with the local address bit of the MAC address rule.

- src/Mayaqua/Mayaqua.c
- src/Mayaqua/Mayaqua.h
- src/Mayaqua/Microsoft.c
- src/Mayaqua/Microsoft.h
- src/vpnbridge/vpnbridge.c
- src/vpnclient/vpncsvc.c
- src/vpncmd/vpncmd.c
- src/vpncmgr/vpncmgr.c
- src/vpndrvinst/vpndrvinst.c
- src/vpninstall/vpninstall.c
- src/vpnserver/vpnserver.c
- src/vpnsetup/vpnsetup.c
- src/vpnsmgr/vpnsmgr.c
- Preventing the Win32 API LoadLibrary() current directory DLL injection issue.
- When loading the DLL file by the LoadLibrary() function in Windows VPN programs, we changed the behavior not to search the current directory. Based on this improvement, even if there are untrusted DLL files in the current directory, it is now safe to avoid the problem of unexpected security problem caused by the default loading behavior of Windows. Acknowledgments: This is based on a report by Herman Groeneveld, aka Sh4d0wman.
Could you please choose …
> Preventing the Win32 API LoadLibrary() current directory DLL injection issue.

- src/CMakeLists.txt
Dear devs,
with the move to cmake (thanks!) we can now shift around the installation. Unfortunately by now the location of the installed vpn programs is hardcoded into PREFIX/vpnxxxx.
The current pull request moves the 4 vpnxxx directories under `PREFIX/libexec/softether`, that is by default `/usr/local/libexec/softether/vpnbridge` etc.
SoftEther VPN Patch Acceptance Policy: 1
> follow FHS and install programs into PREFIX/libexec/softether/vpnxxxx

- src/Cedar/Admin.c
Hubname has to be set after copy or it will be an empty string. To get the real hubname (correct casing) we use it directly from the hub instead of the given parameter
- Set hubName after copy from hub because otherwhise its an empty string
- Option 1
I hereby agree in advance that my work will be licensed automatically under the Apache License or a …
> HubName has to be set after Copy

- debian/changelog
- fix of Launchpad build (see https://launchpadlibrarian.net/376355504/buildlog.txt.gz)
- 
- 
- one
> changelog was not correct from Launchpad point of view

- src/Cedar/Interop_OpenVPN.c
- src/Cedar/Interop_OpenVPN.h
- src/bin/hamcore/openvpn_sample.ovpn
OpenVPN sends the default gateway's MAC address, if the option **--push-peer-info** is enabled.
It also sends the client's environment variables whose names start with `UV_`.
From OpenVPN's [documentation](https://community.openvpn.net/openvpn/wiki/Openvpn23ManPage):
```
Push additional information about the client to server. The following data is always pushed to the server:
IV_VER=<version> -- the client OpenVPN version
IV_PLAT=[linux|solaris|openbsd|mac|netbsd|freebsd|win] -- the client OS platform
IV_LZO_STUB=1 -- if client was built with LZO stub capability
IV_LZ4=1 -- if the client supports LZ4 compressions.
IV_RGI6=1 -- if the client supports --redirect-gateway for ipv6
IV_PROTO=2 -- if the client supports peer-id floating mechansim
IV_NCP=2 -- negotiable ciphers, client supports …
```
> OpenVPN: hostname support

- src/Cedar/IPsec_IPC.c
This allows a DHCP server to use the client ID as unique identifier, in order to correctly assign a static lease.
Previously this wasn't possible, as the client identifier was set to its MAC address, which is randomly generated.
Related issue: #449.
---
> IPC: use hostname as client identifier, if available

- src/Mayaqua/Encrypt.c
- src/Mayaqua/Kernel.c
- Two fixes regarding time usage on X509 certificates
- one
> Certificate date fixes

- src/CMakeLists.txt
- don't treat pthreads like a normal lib
- compile will fail on systems with musl or none stubed pthread
- Option 1
> CMake: fix pthread detection

- src/Mayaqua/Encrypt.c
This pull request improves `FreeOpenSSLThreadState()` and `FreeCryptLibrary()`, in order to clean up the library correctly.
https://wiki.openssl.org/index.php/Library_Initialization#Cleanup
---
> Encrypt: improve FreeOpenSSLThreadState() and FreeCryptLibrary(), in order to clean up the library correctly

- src/BuildAll.cmd
- src/BuildUtil/Win32BuildUtil.cs
- reduce app veyor build log from 29771 to 29009 lines
- 
- 
- one
> Windows: suppress detailed build output

- src/Mayaqua/Encrypt.c
- src/Mayaqua/Encrypt.h
This pull request also fixes the problem described in #31, which was caused by the test key generated in RsaCheck() being too small for newer OpenSSL versions.
---
> Encrypt: set default RSA key size to 1024 everywhere, using the RSA_KEY_SIZE macro

- src/Cedar/BridgeUnix.c
- src/Cedar/BridgeUnix.h
- Switch from DLPI style 2 to DLPI style 1 attachment, based on opening network device (/dev/bge0) rather than root device (/dev/bge)
- Prefer devices located in /dev/net, if present, which is used by Illumos and Solaris 10+
- Should allow SoftEther to work properly with vanity nics and Crossbow vnics present on Solaris 10+ and Illumos while retaining compatibility with older Solaris versions (provided that network interface has its own device node).
You may use this patch as necessary (contribution option 1).
> Solaris: use DLPI style 1 attachment and check for /dev/net used by Illumos and Solaris 10+.

- src/CMakeLists.txt
- src/Cedar/CMakeLists.txt
- src/Mayaqua/CMakeLists.txt
- src/hamcorebuilder/CMakeLists.txt
- src/vpnbridge/CMakeLists.txt
- src/vpnclient/CMakeLists.txt
- src/vpncmd/CMakeLists.txt
- src/vpnserver/CMakeLists.txt
This pull request splits `src/CMakeLists.txt` so that each subproject has its own CMake file.
---
> src: split CMakeLists.txt for each subdirectory

- src/Mayaqua/Encrypt.c
-  FIPS mode and openssl compression could have been compiled out on target platform and results in undefined refs
- added defines to check for `OPENSSL_FIPS` and `OPENSSL_NO_COMP`
- option 1
I hereby agree in advance that my work will be licensed automatically under the Apache License or a similar BSD/MIT-like open-source license in case the SoftEther …
> Encrypt.c: check whether OpenSSL compression and FIPS features are available

- .travis.yml
- CMakeLists.txt
- configure
- src/CMakeLists.txt
- src/Cedar/CMakeLists.txt
- src/Mayaqua/CMakeLists.txt
- use "modern" cmake 3.4.3 _(released in 2015)_ lib features for better cross-platform lib detection
- moved (readline, curses) libs to cedar
cmake docu:
https://cmake.org/cmake/help/v3.4/module/FindThreads.html
https://cmake.org/cmake/help/v3.4/module/FindOpenSSL.html
https://cmake.org/cmake/help/v3.4/module/FindCurses.html
https://cmake.org/cmake/help/v3.4/module/FindZLIB.html
- Option 1
PRELIMINARY DECLARATION …
> CMake: use find_package() and link Cedar to Ncurses

- src/BUILD_UNIX.md
Just a quick typo fix that was driving me mad :laughing: 
- 
- 
- 
-
> Fixed typo in docs

- .gitmodules
- src/Mayaqua/CMakeLists.txt
- src/Mayaqua/Encrypt.c
> Mayaqua: use "cpu_features" to check whether AES-NI is supported

- src/Mayaqua/Unix.c
> Unix.c: don't use hardcoded path to call "ethtool"

- src/Cedar/Admin.c
HubName == NULL  always evaluated as "false", so we can remove it
- some minor cleanup, make coverity more happy
- 
- 
- one
> src/Cedar/Admin.c: remove unused condition, make coverity scan cleaner

- src/Cedar/CM.c
- src/Cedar/CMInner.h
- src/Cedar/Client.c
- src/Cedar/Client.h
- src/Cedar/Command.c
- src/Cedar/Command.h
- src/Cedar/Protocol.c
- src/bin/hamcore/strtable_cn.stb
- src/bin/hamcore/strtable_en.stb
- src/bin/hamcore/strtable_ja.stb
- src/bin/hamcore/strtable_ko.stb
- src/bin/hamcore/strtable_tw.stb
With server certificate validation enabled, vpnclient unconditionally
stopped connection on untrusted server certificate. Added account
configuration parameter to retry connection if server certivicate failed
validation.
We have a large number of headless devices connecting to our softether instance and have identified this as a permanent failure mode in the client code in a case where the server's certificate has expired or the server is started with a default config.
Since these are headless devices on disparate and inaccessable networks, it is essential for us that the client continue retrying it's connection even to a misconfigured server. Once the server configuration issue is resolved the client should be able to successfully connect.
I don't know if this needs a configuration …
> Retry connection on untrusted server certificate

- debian/rules
- launchpad does not support git submodules by itself, so we need to add git modules checkout by ourselves
- 
- 
- one
> recursive git checkout for launchpad

- .gitlab-ci.yml
- ubuntu package builds for 14.04, 16.04, 18.04 on gitlab.com
- 
- 
- one
> add debian package builds to gitlab-ci.yml

- .gitignore
- CMakeLists.txt
check whether cloned recursively during cmake build
- additional error message if cloned without submodules
- 
- 
- one
> ignore temp cmake files, check whether cloned recursively

- debian/control
(we need it to checkout submodules)
- specify "git" as build dependency for debian packages (required for submodules checkout)
- 
- 
- one
> launchpad builds: add "git" as a build dependency

- src/Cedar/Logging.c
- src/Mayaqua/Mayaqua.c
- src/Mayaqua/Mayaqua.h
- src/Mayaqua/Unix.c
- src/Mayaqua/Unix.h
- src/bin/hamcore/strtable_en.stb
This is the first in couple of patches to make softether compatible with running inside an immutable, stateless, container. We currently run softether on top of kubernetes as a docker container and have run into a number of design decisions that make it very difficult.
In a containerized infrastructure, it is almost a rule that processes do not daemonize and direct their logging output to stdout. This is because the container process runs as PID 0 inside the container, and the process's stdout is collected by the infrastructure logging facility.
- Create a `--foreground` command line option so that the service does not daemonize
- In foreground mode the service will log only to stdout and not to log files
Your great patch is much appreciated. We are …
> Foreground logging

- src/bin/hamcore/strtable_cn.stb
- src/bin/hamcore/strtable_en.stb
- src/bin/hamcore/strtable_ja.stb
- src/bin/hamcore/strtable_ko.stb
- src/bin/hamcore/strtable_tw.stb
Committer: MtCedarNet <mtcedar@hotmail.com>
- The notation 'Do not use TLS 1.0' on the UI is currently misleading as it supports TLS 1.1 or later, so modify it to the notation 'Use SSL 3.0'.
- choose 1
> Change 'Don't use TLS' to 'Use SSL 3.0' to clarify the danger.

- debian/rules
launchpad builds are missing ".git" subfolder, probably
because of deleting them during "clean" stage
- reordering of "git submodules checkout" to very early stage
- 
- 
- one
I hereby agree in advance that my work will be licensed automatically under the Apache License or a similar BSD/MIT-like open-source license in case the SoftEther VPN Project …
> debian: try to initialize submodules on very early stage

- src/Cedar/Console.c
- src/Cedar/VLanUnix.h
```c
In file included from /builds/SoftEther/SoftEtherVPN/src/Cedar/Bridge.c:130:0:
/builds/SoftEther/SoftEtherVPN/src/Cedar/BridgeUnix.c: In function 'CloseEth':
/builds/SoftEther/SoftEtherVPN/src/Cedar/BridgeUnix.c:1568:3: warning: implicit declaration of function 'FreeTap'; did you mean 'FreeCaps'? [-Wimplicit-function-declaration]
FreeTap(e->Tap);
^~~~~~~
FreeCaps
```
```c
/builds/SoftEther/SoftEtherVPN/src/Cedar/Console.c: In function 'PasswordPrompt':
/builds/SoftEther/SoftEtherVPN/src/Cedar/Console.c:2051:8: warning: implicit declaration of function 'getch'; did you mean 'getc'? [-Wimplicit-function-declaration]
c = getch();
^~~~~
getc
```
---
> Cedar: fix implicit function declaration warnings

- src/CMakeLists.txt
- src/Mayaqua/Internat.c
As previous discussion on my previous pull request, I implemented musl support (which is a small change in Internat.c file) using conditional compilation, so that default behaviour is unchanged, and using a new environment variable allows musl compilation to work.
Summary of previous discussion:
- musl has a bug in iconv() function, which cause softether to compile correctly, but exhibit a bad runtime behaviour: any string conversion fails because iconv initialization fails early;
- to correct this bug, I used the same workaround that was already used to compile on macOS, see Internat.c diff and this is self-evident;
- workaround is triggered compile-time by the UNIX_LINUX_MUSL #define flag;
- cmake has been modified to add the -DUNIX_LINUX_MUSL command line flag to gcc when the …
> musl support

- src/BUILD_UNIX.md
- reorder "cd ..." and "git submodule" commands
- 
- 
- one
> src/BUILD_UNIX.md: Reorder commands of SE manual build with musl

- src/Mayaqua/Encrypt.c
* fix invalid features.aes for mips, ppc (fixes #651)
option 1
> Mayaqua/Encrypt.c: fix invalid features.aes for mips, ppc

- src/Cedar/EtherLog.c
- src/Cedar/EtherLog.h
- it is wrong to use "e == NULL" in https://github.com/SoftEtherVPN/SoftEtherVPN/blob/master/src/Cedar/EtherLog.c#L284, it should be "r->Param == NULL"
- 
- 
- one
I hereby agree in advance that my work will be licensed automatically under the Apache License or a similar BSD/MIT-like open-source license in case the SoftEther VPN Project adopts such a …
> src/Cedar/EtherLog: remove null dereference introduced in #650

- .gitlab-ci.yml
`CMakeLists.txt` requires at least CMake 3.6, but Ubuntu Trusty and Xenial have 3.5.1.
---
> GitLab: compile and install latest version of CMake

- .gitlab-ci.yml
It's used to download the CMake source code archive from its website.
---
> GitLab: install "wget"

- src/Cedar/IPsec_IPC.c
- src/Cedar/IPsec_IPC.h
- src/Cedar/Interop_OpenVPN.c
- src/Cedar/Interop_OpenVPN.h
The workaround was required for the "net30" topology because:
```
There is a problem in your selection of --ifconfig endpoints [local=192.168.30.10, remote=192.168.30.1]. The local and remote VPN endpoints must exist within the same 255.255.255.252 subnet. This is a limitation of --dev tun when used with the TAP-WIN32 driver. Try 'openvpn --show-valid-subnets' option for more info.
```
https://github.com/OpenVPN/openvpn/blob/a6fd48ba36ede465b0905a95568c3ec0d425ca71/src/openvpn/tun.c#L3719-L3750
See https://community.openvpn.net/openvpn/wiki/Topology for detailed info.
---
> Interop_OpenVPN: set "subnet" topology and remove workaround for "net30" topology on Win32

- src/Cedar/EtherLog.c
- src/Cedar/EtherLog.h
- coverity warns to "check" return value of function
- 
- 
- one
> resolve cosmetic coverity issues

- src/Cedar/Virtual.c
- Fixed a problem that TCP sessions of virtual NAT will be closed even if the outbound buffer is not empty
- one
> Fix that virtual NAT session is closed even if data remains.

- src/Cedar/Client.c
[src/Cedar/Client.c:9094]: (style) Unused variable: i
[src/Cedar/Client.c:500] -> [src/Cedar/Client.c:503]: (style) Variabl
- remove redundant "if"
- remove unused variable
- one
-
I hereby agree in advance that my work will be licensed automatically under the Apache License or a similar BSD/MIT-like open-source license in case the SoftEther VPN …
> src/Cedar/Client.c: remove redundant "if" statement, unused variable

- src/Neo6/NDIS6.c
Possible security problem under double-fetch conditions. Microsoft says all ProbeForRead calls should be treated as if they could throw exceptions.  SRC: https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-probeforread
I choose Contribution option (1)
> Added Try+Except block for ProbeForRead

- src/Mayaqua/Network.c
- resolve couple of coverity "issues"
- 
- 
- one
> src/Mayaqua/Network.c: silence coverity on "Unchecked return value"

- src/Cedar/BridgeUnix.c
> Cedar: fix segmentation fault during local bridge creation on FreeBSD

- src/Mayaqua/Unix.c
`clock_gettime()` was implemented in macOS 10.12.
This may also fix #47, as @Schouwenburg mentioned that the server started crashing after updating to version `4.06.9433`, which contains 4c48388b1235faa91cf377a8d238871cb5184e3b:
https://github.com/SoftEtherVPN/SoftEtherVPN/blob/e530932df61d2e6a1c5b07374c9817d5cdc4295b/src/Mayaqua/Unix.c#L2097-L2109
Resources are not freed, as `mach_port_deallocate()` is never called.
---
> Unix.c: remove macOS-specific UnixGetTick64() implementation

- src/Mayaqua/Unix.c
refactoring was discussed in PR#672
- unused variable removed
- readability of ifdef improved
- 
- one
> src/Mayaqua/Unix: remove unused code, improve readability of "ifdef"

- src/Cedar/Cedar.h
- src/Cedar/VLanUnix.c
- Add custom TAP interface name support for FreeBSD.
- Increase the maximum number of TAP devices to iterate through from 16 to 512.
- Refactor `UnixCreateTapDeviceEx()`.
---
> Cedar: custom TAP interface name support for FreeBSD, function refactor

- src/Cedar/Cedar.h
- src/Cedar/Cedar.vcproj
- src/Cedar/IPC.c
- src/Cedar/IPC.h
- src/Cedar/Proto_EtherIP.c
- src/Cedar/Proto_EtherIP.h
- src/Cedar/Proto_IKE.c
- src/Cedar/Proto_IKE.h
- src/Cedar/Proto_IPsec.c
- src/Cedar/Proto_IPsec.h
- src/Cedar/Proto_IkePacket.c
- src/Cedar/Proto_IkePacket.h
- src/Cedar/Proto_L2TP.c
- src/Cedar/Proto_L2TP.h
- src/Cedar/Proto_OpenVPN.c
- src/Cedar/Proto_OpenVPN.h
- src/Cedar/Proto_PPP.c
- src/Cedar/Proto_PPP.h
- src/Cedar/Proto_SSTP.c
- src/Cedar/Proto_SSTP.h
- src/Cedar/Proto_Win7.c
- src/Cedar/Proto_Win7.h
- src/Cedar/Proto_Win7Inner.h
- Rename `IPsec_IPC` to `IPC`, as it's not related to third-party protocols.
- Replace `Interop_` and `IPsec_` with `Proto_` in the protocol-specific source/header files' names so that it's clear that they are all third-party protocols.
---
> Cedar: replace "Interop_" and "IPsec_" with "Proto_" in the protocol-specific source/header files' names

- src/Cedar/Proto_IkePacket.c
Fixes #552.
#294 added SHA-256, SHA-384, and SHA-512 support to the protocol, but part of it was removed in faee11ff096e7950b006ef1ae8dc636b6fe0131e, because it caused a buffer over-read crash.
It also broke the MD5 implementation because the switch-case block doesn't handle the type anymore:
https://github.com/SoftEtherVPN/SoftEtherVPN/blob/8fdd224ba7f5676f99d74c7c63f60e046d07ec97/src/Cedar/Proto_IkePacket.c#L2982-L2996
This pull request fixes all the implementations and improves the `IkeHMac()` function by using the dedicated hashing functions.
---
> Proto_IkePacket.c: fix MD5, SHA-256, SHA-384 and SHA-512 implementation

- src/Cedar/BridgeUnix.c
- proposed fix for CID 305724 and CID 305725 by removing unneeded loop structures.
- Option 1
> Clean up Solaris device name parsing code to eliminate Coverity errors

- src/Cedar/SW.c
- src/Mayaqua/Microsoft.c
- src/Mayaqua/Unix.c
- src/hamcorebuilder/hamcorebuilder.c
- src/vpncmd/vpncmd.c
- src/vpncmgr/vpncmgr.c
- src/vpndrvinst/vpndrvinst.c
- src/vpninstall/vpninstall.c
- src/vpnsmgr/vpnsmgr.c
This pull request changes all the calls to `InitMayaqua()` so that the memory check and debug functions are enabled if `DEBUG` is defined.
---
> Enable debug messages and memory check with debug configuration

- .appveyor.yml
AppVeyor recently added Ubuntu 16.04 and 18.04 images, which we can use to provide downloadable packages.
---
> AppVeyor: add Ubuntu 16.04 and 18.04 builds

- src/bin/hamcore/strtable_cn.stb
- src/bin/hamcore/strtable_ja.stb
- src/bin/hamcore/strtable_ko.stb
- src/bin/hamcore/strtable_ru.stb
- src/bin/hamcore/strtable_tw.stb
-  sync localization files before merging PR#712
- one
> fix localization files, missing strings were taken from "en"

- src/Cedar/Client.c
- src/Cedar/Hub.c
> src/Cedar: resolve possible null pointer dereference and silence dead code warning

- CMakeLists.txt
> cmake: compare PROJECT_VERSION against src/CurrentBuild.txt

- src/Cedar/BridgeUnix.c
Fixes #723.
Local bridge support for BSD systems was added in #670 and #706.
---
> BridgeUnix.c: enable local bridge function on all BSD systems

- AUTHORS.TXT
This pull request updates the contributors list and changes the format to the one used by Git, with the output of the command `git log --format='%aN <%aE>' | sort -f | uniq`.
Email addresses ending with `@users.noreply.github.com` are replaced with the GitHub profile links.
---
> AUTHORS.TXT: update contributors list using "git log --format='%aN <%aE>' | sort -f | uniq"

- src/Cedar/SW.c
- src/Mayaqua/Microsoft.c
- src/Mayaqua/Unix.c
- src/vpncmd/vpncmd.c
- src/vpncmgr/vpncmgr.c
- src/vpndrvinst/vpndrvinst.c
- src/vpninstall/vpninstall.c
- src/vpnsmgr/vpnsmgr.c
1. ifdef DEBUG -> defined(_DEBUG) || defined(DEBUG)
In VC++ compilers, the macro is "_DEBUG", not "DEBUG".
2. If set memcheck = true, the program will be vitally slow since it will log all malloc() / realloc() / free() calls to find the cause of memory leak.
For normal debug we set memcheck = false.
Please set memcheck = true if you want to test the cause of memory leaks.
-
I hereby agree …
> Debug flag and test mode improvements

- src/Mayaqua/MayaType.h
This pull request solves the following warnings:
```
warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
#define POINTER_TO_KEY(p)  ((sizeof(void *) == sizeof(UINT)) ? (UINT)(p) : HashPtrToUINT(p))
^
warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
#define UINT64_TO_POINTER(i) ((sizeof(void *) == sizeof(UINT64)) ? (void *)(i) : (void *)((UINT)(i)))
^
warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
#define POINTER_TO_UINT64(p) (((sizeof(void *) == sizeof(UINT64)) ? (UINT64)(p) : (UINT64)((UINT)(p))))
^
```
---
> MayaType.h: fix pointer casting warnings

- src/Mayaqua/Memory.c
This pull request fixes the `TrackDeleteObj: 0x12345678 is not Object!!` (where `0x12345678` is the actual address) errors with `memcheck` enabled .
It also fixes the following related warnings:
```
warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
TrackChangeObjSize((DWORD)addr, size, (DWORD)new_addr);
^
warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
TrackChangeObjSize((DWORD)addr, size, (DWORD)new_addr);
^
```
---
> Memory.c: fix pointer cast in TrackChangeObjSize() call

- .travis.yml
- src/CMakeLists.txt
- src/vpnbridge/CMakeLists.txt
- src/vpnclient/CMakeLists.txt
- src/vpncmd/CMakeLists.txt
- src/vpnserver/CMakeLists.txt
- src/vpntest/CMakeLists.txt
This results in a faster build and less space required.
---
> CMake: build all targets in the same directory, so that "hamcore.se2" doesn't have to be copied for each of them

- CMakeLists.txt
- src/Cedar/CMakeLists.txt
- src/Mayaqua/CMakeLists.txt
The binaries can still be run directly from the build directory.
A new package containing the shared libraries is built, but they are not marked as dependencies by CMake. It's something we should fix as soon as possible.
---
> CMake: build Cedar and Mayaqua as shared libraries, create "common" package

- src/vpnbridge/CMakeLists.txt
- src/vpnclient/CMakeLists.txt
- src/vpnserver/CMakeLists.txt
> CMake: change ${CMAKE_SOURCE_DIR}/tmp with ${CMAKE_BINARY_DIR}

- .travis.yml
> travis-ci: fix osx build, remove unneeded "apt" plugin (it is unused since CPack)

- src/vpntest/vpntest.c
> vpntest: return non zero on invalid syntax

- .gitignore
- src/Mayaqua/Table.c
- Fix a single memory leak in loading the string table.
- Add .suo (Visual Studio user setting) file to the .gitignore file.
-
> Fix a single memory leak in loading the string table

- src/Mayaqua/Encrypt.c
> src/Mayaqua/Encrypt.c: fix memory leak occasionally found by valgrind

- .travis.yml
> travis-ci: add "vpntest" memory checks

- .gitlab-ci.yml
> gitlab-ci: add "vpntest" memory tests

- src/BUILD_UNIX.md
Provide required preparation on macOS to build SoftEtherVPN (development repo) from source.
-
> docs(BUILD_UNIX): add macOS specifics

- src/Cedar/Proto_OpenVPN.c
- src/Cedar/Proto_OpenVPN.h
- src/Mayaqua/Encrypt.c
- src/Mayaqua/Encrypt.h
- src/bin/hamcore/openvpn_sample.ovpn
This pull requests adds support for GCM ciphers to the OpenVPN protocol.
---
> Cedar/Proto_OpenVPN: add support for GCM ciphers

- src/BUILD_WINDOWS.md
-  Added Windows CMake development information as the config added support for it
- 1
I also agree to my work being licensed under a non GPL license anytime in the future.
I'm planning to sometime soon (hopefully) create a GitHub Wiki entry for development on Windows, though that will be in the future.
Feel free to point out any grammar/spelling mistakes and I'll be happy to correct them.
> Added Windows CMake setup info

- src/Cedar/Proto_PPP.c
Fixes #114.
`1.0.0.1` is a real IP address, owned by CloudFlare and used for their DNS service.
This commit changes the IP address we push to `192.0.0.8`, which is defined in RFC7600 as dummy IPv4 address.
---
> Cedar/Proto_PPP.c: push 192.0.0.8 instead of 1.0.0.1 as gateway IP address

- src/BUILD_WINDOWS.md
- src/Neo/Neo.rc
- src/Neo6/Neo6.rc
- src/PenCore/PenCore.rc
- src/See/See.rc
- src/SeeDll/SeeDll.rc
- src/Wfp/Wfp.rc
- src/vpn16/Vpn16.rc
- src/vpnbridge/vpnbridge.rc
- src/vpnclient/vpnclient.rc
- src/vpncmd/vpncmd.rc
- src/vpncmdsys/vpncmdsys.rc
- src/vpncmgr/vpncmgr.rc
- src/vpndrvinst/vpndrvinst.rc
- src/vpninstall/vpninstall.rc
- src/vpnserver/vpnserver.rc
- src/vpnsetup/vpnsetup.rc
- src/vpnsmgr/vpnsmgr.rc
- src/vpntest/vpntest.rc
Visual Studio 2008 included `afxres.h` even if not required.
---
> src: change "afxres.h" to "winres.h" in all resource files, to remove MFC dependency

- .gitlab-ci.yml
> gitlab-ci: enable SAST

- .travis.yml
> travis-ci: run Coverity only after openssl is built

- src/Cedar/Cedar.h
- src/Cedar/Proto_PPP.c
- src/Cedar/Server.c
> Cedar: add new "UsernameHubSeparator" configuration option for the server, to specify a different character from '@'

- CMakeLists.txt
- src/BuildFiles/VerScript/ver.rc
- src/BuildUtil/Win32BuildUtil.cs
- src/CMakeLists.txt
- src/Cedar/CMakeLists.txt
- src/Mayaqua/CMakeLists.txt
- src/PenCore/CMakeLists.txt
- src/hamcorebuilder/CMakeLists.txt
- src/vpnbridge/CMakeLists.txt
- src/vpnclient/CMakeLists.txt
- src/vpncmd/CMakeLists.txt
- src/vpncmgr/CMakeLists.txt
- src/vpnserver/CMakeLists.txt
- src/vpnsmgr/CMakeLists.txt
- src/vpntest/CMakeLists.txt
- Changes the versioning resource template so that it uses CMake's variables syntax.
- Configure CMake so that it uses the versioning resource template for each target.
- Edit `BuildUtil` so that it uses the new variables.
---
> CMake: build targets with versioning info on Windows

- .appveyor.yml
> AppVeyor: shorten artifacts path, move github token to variables

- .appveyor.yml
- .gitlab-ci.yml
> CI: avoid not needed builds, make AppVeyor upload src with submodules

- src/Cedar/Cedar.c
- src/Cedar/Cedar.h
- src/Cedar/Proto_OpenVPN.c
- src/Cedar/Server.c
Added the "OpenVPNPushDummyIPv4AddressOnL2Mode" option for the OpenVPN L2 mode.
To fix the bug of OpenVPN 2.4.6 and particular version of kernel mode TAP driver on Linux, the TAP device must be up after the OpenVPN client is connected. However there is no direct push instruction to do so to OpenVPN client. Therefore we push the dummy IPv4 address (RFC7600) to the OpenVPN client to enforce the TAP driver UP state.
- 1
PRELIMINARY DECLARATION FOR FUTURE …
> Added the "OpenVPNPushDummyIPv4AddressOnL2Mode" option for the OpenVPN L2 mode.

- src/Mayaqua/Encrypt.c
- SHA-0 Implementation replacement from GPLv3 to Apache License
-1
> SHA-0 Implementation replacement from GPLv3 to Apache License

- src/Mayaqua/Memory.c
- src/Mayaqua/Memory.h
- src/Mayaqua/Network.c
- Revamp `RecvHttpHeader()` so that cleanup functions are not called twice.
- Add new `FreeSafe()` function which frees the memory and sets the passed pointer's value to `NULL`. It's useful to guarantee that freed area is not accessed with that pointer (it causes a segmentation fault). This also allows to safely call cleanup functions multiple times.
Both changes solve the crash I experienced:
```c
#0  0x00007fd306127e22 in FreeToken (tokens=0x560a0090ba40) at /src/Mayaqua/Str.c:2353
#1  0x00007fd306120653 in RecvHttpHeader (s=s@entry=0x7fd2f00fc840) at /src/Mayaqua/Network.c:20608
#2  0x00007fd30645ba98 in ServerDownloadSignature (c=c@entry=0x560a00909060, error_detail_str=error_detail_str@entry=0x7fd2e74399a0) at /src/Cedar/Protocol.c:5665
#3 …
```
> Mayaqua: fix segmentation fault, add new FreeSafe() function

- src/Cedar/IPC.c
- src/Cedar/Protocol.c
`PackLoginWithOpenVPNCertificate()` returned `NULL` without calling `FreePack()` on the allocated object.
---
> Cedar/IPC.c: fix memory leak occurring when both the username and common name are not present (OpenVPN)

- src/Mayaqua/Memory.h
- src/Mayaqua/Network.c
`FreeSafe()` (introduced in #841) needs an argument of type `void **` (pointer to pointer), so that it can set the pointer's value to `NULL` once the memory is freed.
Pointers of different data types are implicitly converted to `void *` when required, however it's not the case for `void **` (it results in a compiler warning).
The new `PTR_TO_PTR` macro does the required conversion, allowing to write:
```c
char *str = Malloc(1);
FreeSafe(PTR_TO_PTR(str));
```
instead of:
```c
char *str = Malloc(1);
FreeSafe((void **)&str));
```
---
> Mayaqua: add "PTR_TO_PTR" macro intended to be used with FreeSafe()

- .travis.yml
> travis-ci: try to fix coverity scan

- src/Mayaqua/Network.c
- src/Mayaqua/Network.h
This fixes the following crash:
```c
#0  FreeHttpValue (value=0x25) at /src/Mayaqua/Network.c:20822
#1  0x00007fe160af5cb3 in FreeHttpHeader (header=0x7fe150021170) at /src/Mayaqua/Network.c:20846
#2  0x00007fe160e31b43 in ServerDownloadSignature (c=c@entry=0x7fe15000b350, error_detail_str=error_detail_str@entry=0x7fe15df559a0) at /src/Cedar/Protocol.c:5851
#3  0x00007fe160e341f9 in ServerAccept (c=c@entry=0x7fe15000b350) at /src/Cedar/Protocol.c:1290
#4  0x00007fe160dee261 in ConnectionAccept (c=c@entry=0x7fe15000b350) at /src/Cedar/Connection.c:3125
#5  0x00007fe160e07ffa in TCPAcceptedThread (t=<optimized out>, param=<optimized out>) at /src/Cedar/Listener.c:273
#6  0x00007fe160ad7c05 in ThreadPoolProc (t=0x55d33eda5620, param=0x55d33edc3c20) at /src/Mayaqua/Kernel.c:983
#7 …
```
> Mayaqua: fix segmentation fault, add new FreeHttpHeaderSafe() function

- src/Cedar/Admin.c
- src/Mayaqua/Network.c
- src/bin/hamcore/vpninstall_cn.inf
Fixes #861.
---
`SSL_free()` also frees the associated context.
https://github.com/openssl/openssl/blob/d6c3c1896cf3c0d69bc27da923d63f8130b13ca0/ssl/ssl_lib.c#L1209
From https://www.openssl.org/docs/man1.1.1/man3/SSL_free.html:
> SSL_free() also calls the free()ing procedures for indirectly affected items, if applicable: the buffering BIO, the read and write BIOs, cipher lists specially created for this **ssl**, the **SSL_SESSION**. Do not explicitly free these indirectly freed up items before or after calling SSL_free(), as trying to free things twice may lead to program failure.
---
https://github.com/SoftEtherVPN/SoftEtherVPN/blob/e939f887c45e5c092bf5c8b69d5c187448d52c9e/src/Cedar/Admin.c#L8157-L8159
`StrCat()` appends a string to an already existing string. In order to know where the …
> Fix crashes in GetCipherList() and StGetServerCipherList()

- src/Cedar/Cedar.c
Server Manager GUI shows incorrect server and client version in some windows. It is caused by an inconsistency between version number [generating code](https://github.com/SoftEtherVPN/SoftEtherVPN/blob/63c01ba736a4cd4ab75ba82ab34a3fdcf235a115/src/Cedar/Cedar.c#L1419-L1426) and [formatting code](https://github.com/SoftEtherVPN/SoftEtherVPN/blob/63c01ba736a4cd4ab75ba82ab34a3fdcf235a115/src/Cedar/Protocol.c#L1602). This patch fixes it.
> Fix to show correct version in Server Manager GUI

- src/BuildFiles/VerScript/ver.rc
This patch fixes the trademark statement in `ver.rc` file that indicates `United Status`. (misspelling of `United States`?)
> ver.rc: fix misspelling

- src/Mayaqua/Network.c
- SecureSend is labeled as SecureRecv in debug messages
- 
-
> Fixed wrong function name in Debug message

- README.md
Old link was wrong, new one have instructions on how to use the PPA.
option: 1
> Adjust launchpad ppa links

- .gitlab-ci.yml
Hello, 
Following up on #881, attached is a basic CI definition for illumos that I've tested on my private fork of SoftEtherVPN on gitlab[1]. 
The basic changes over a standard "out of the box" build are to force 64 bit mode and to look in /opt/local for non-system libraries (such as readline, etc)
I can link my illumos runner to this project if given a CI runner registration token.
[1] https://gitlab.com/hww3/SoftEtherVPN/
> Add basic CI definition for illumos

- .gitlab-ci.yml
- add attribution to the illumos build job
- remove stage specification on job so that other jobs don't wait for it
> illumos: remove stage and document the runner's maintainer

- src/Cedar/Proto_OpenVPN.c
- OpenVPN X.509 certificate authentication will be used only when no username / password is specified
- 
-
> OpenVPN X.509 certificate authentication will be used only when no username / password is specified

- src/Cedar/Admin.c
found by Coverity
*** CID 341551:  Incorrect expression  (NO_EFFECT)
/src/Cedar/Admin.c: 414 in AdminWebHandleFileRequest()
408     // Handle the file request
409     bool AdminWebHandleFileRequest(ADMIN *a, CONNECTION *c, SOCK *s, HTTP_HEADER *h, char *url_src, char *query_string, char *virtual_root_dir, char *physical_root_dir)
410     {
411             bool ret = false;
412             char url[MAX_PATH];
413             UINT i, len;
>>>     CID 341551:  Incorrect expression  (NO_EFFECT)
>>>     Comparing an array to null is not useful: "url == NULL", since the test will always evaluate as true.
414             if (a == NULL || c == NULL || s == NULL || h == NULL || url == NULL || query_string == NULL ||
415                     virtual_root_dir == NULL || physical_root_dir == NULL)
416 …
> src/Cedar/Admin.c: remove redundant check

- src/Mayaqua/Mayaqua.h
Fixes warning from the musl libc:
warning redirecting incorrect #include <sys/poll.h> to <poll.h>
> Mayaqua: Replace GNU specific sys/poll.h header with POSIX poll.h

- src/Mayaqua/Encrypt.c
- src/Mayaqua/Secure.c
Initialization and deinitialization are deprecated.
Missing headers were added.
Explicit threading is also deprecated.
> Mayaqua: Fix compilation without deprecated OpenSSL APIs

- src/Cedar/Virtual.c
- src/Cedar/Virtual.h
Fixes #944.
A race condition in the DHCP server caused it to offer the same IP address to multiple clients when they connected at the same time, because an offered IP address was considered free until the final step (`DHCP_ACK`).
This commit introduces a list to keep track of the pending leases created during `DHCP_OFFER`, so that an IP address is guaranteed to be offered to a single client.
> Virtual: fix race condition in DHCP server which resulted in multiple clients receiving the same IP

- src/Mayaqua/Microsoft.c
- src/Mayaqua/Microsoft.h
- src/vpntest/vpntest.c
Enables crash minidump for Win32 vpntest.
Minidump files will be saved to:
- `C:\Users\<username>\AppData\Local\Temp\vpn_debug` (for normal user)
- `src\bin\vpn_debug` (for administrator user).
> Enable crash minidump for Win32 vpntest

- src/Cedar/Virtual.c
If SecureNAT is enabled and the hostname of the server
is longer than 16characters, every NETBIOS name resolution
query triggers the buffer overflow. If the server was built
with stack protection, the process will be killed.
> Fix buffer overflow during NETBIOS name resolution

- src/Cedar/Account.c
- src/Cedar/Account.h
- src/Cedar/Connection.h
- src/Cedar/Hub.c
- src/Cedar/Hub.h
- src/Cedar/IPC.c
- src/Cedar/IPC.h
- src/Cedar/Proto_EtherIP.c
- src/Cedar/Proto_OpenVPN.c
- src/Cedar/Proto_PPP.c
- src/Cedar/Protocol.c
- src/Cedar/Radius.c
- src/Cedar/Radius.h
- src/Cedar/Server.c
- src/Cedar/Server.h
- src/Cedar/Session.c
- src/Cedar/Session.h
- src/Mayaqua/Network.c
- src/Mayaqua/Network.h
- Fixed the problem occurs when RPC messages between Cluster Members exceed 64Kbytes.
- Fixed the RADIUS PEAP client to use the standard TLS versioning.
- Implementation of a function to fix the MAC address of L3 VPN protocol by entering e.g. "MAC: 112233445566" in the "Notes" field of the user information.
- Implementation of a function to fix the virtual MAC address to be assigned to the L3 VPN client as a string attribute from RADIUS server when authentication.
Notes:
We implemented the VPN Server to receive the specification from the RADIUS server as an ASCII character string as RADIUS Attribute "Framed-Interface-Id" (attribute value: 96) defined in RFC 3162.
1. When this function is used, you can fix the virtual MAC address when L3 VPN client for VPN connection to VPN Server in L2TP, …
> Adding RADIUS and L3 MAC address fixing function, with small bug-fixes

- src/Cedar/Protocol.c
The bug was caused by a typo in the `StrCpy()` call: the source buffer was the same as the destination one, meaning that the function didn't do anything.
The feature was introduced in #772.
> Protocol.c: fix bug in ClientConnectGetSocket() causing custom HTTP header not to work

- src/Mayaqua/Mayaqua.h
#1009 introduced a new source file, which doesn't include any standard headers.
The missing include was not spotted because the GitLab CI is not enabled for pull requests.
> Mayaqua.h: include <stdarg.h> for "va_list" on Illumos

- src/Cedar/Proto_OpenVPN.c
`OvsDecrypt()` returns 0 when it fails, resulting in `size` rolling over with an end result of `4294967292`.
This commit fixes the issue by checking whether `size` is greater than `sizeof(UINT)` before performing the subtraction.
---
Fixes #1017.
> Proto_OpenVPN.c: fix segmentation fault in OvsProceccRecvPacket()

- CMakeLists.txt
- src/vpnbridge/CMakeLists.txt
- src/vpnclient/CMakeLists.txt
- src/vpnserver/CMakeLists.txt
Currently the systemd service unit files are installed
into /lib/systemd/system if that directory exists. This
might not be optimal for every user, e.g. when the build
system is not the target system or when building as an
unprivileged user using CMAKE_INSTALL_PREFIX.
Make this configurable by adding a cached cmake variable
CMAKE_INSTALL_SYSTEMD_UNITDIR. Usage:
- install unit files into /lib/systemd/system if it exists (old
behavior)
cmake
- don't install unit files
cmake -D CMAKE_INSTALL_SYSTEMD_UNITDIR=
- install into absolute path
cmake -D CMAKE_INSTALL_SYSTEMD_UNITDIR=/path
- install into path relative to ${CMAKE_INSTALL_PREFIX}
cmake -D CMAKE_INSTALL_SYSTEMD_UNITDIR=path
> Make install dir for unit files configurable

- src/Cedar/Proto_IKE.c
- src/Cedar/Server.c
- src/Cedar/Server.h
Setting it to `true` mitigates [CVE-2002-1623](https://www.cvedetails.com/cve/CVE-2002-1623).
---
Fixes #1030.
> Cedar: add "DisableIPsecAggressiveMode" option

- .cirrus.yml
Hi, I've learned Cirrus CI and made further refinements on FreeBSD CI.
Cirrus CI also has matrix to define multiple build conditions, so I use it. FreeBSD has multiple SSL libraries, so perform build test for each.
* base system OpenSSL
* ports OpenSSL
* ports OpenSSL 1.1.1
* ports LibreSSL
* ports LibreSSL development version
And also perform CI test with supported FreeBSD version 11 and 12.
Also, separate build procedure into prepare, configure, build, and test stage.
> Further FreeBSD CI refinements

- src/Cedar/Virtual.c
- Bugfix: Fix the SecureNAT connection problem with ignoring TCP ECN bit enabled packets
- 
-
> Bugfix: Fix the SecureNAT connection problem with ignoring TCP ECN bit enabled packets

- src/Cedar/Logging.c
- Improvement: Add a space character between URL and other tokens in the packet log format.
- 
-
> Improvement: Add a space character between URL and other tokens in the packet log format.

- .cirrus.yml
- src/Mayaqua/CMakeLists.txt
Formerly, SKIP_CPU_FEATURES is automatically detected by system
processor. However, "^(armv7l|aarch64|s390x)$" does not cover all
processors that cpu_features should be skipped.
"armv6", "armv7", "mips", "mips64" on FreeBSD are examples [1]
that cpu_features is not correctly skipped.
This change intends to build SoftEther without any modifications on
CMakeLists.txt on such processors.
cmake . -DSKIP_CPU_FEATURES=1
[1] https://www.freebsd.org/platforms/
> allow to SKIP_CPU_FEATURES explicitly, not only autodetect 

- .cirrus.yml
testing on a single FreeBSD version is enough.  `-snap` images are
unstable to perform CI test.
> FreeBSD CI: quit freebsd-11-3-snap

- src/Cedar/Protocol.c
- src/Cedar/Sam.c
I also found some code in [BridgeUnix.c](src/Cedar/BridgeUnix.c) used for Solaris platform that likely won't work. Here is a report for [ParseUnixEthDeviceName](https://github.com/SoftEtherVPN/SoftEtherVPN/blob/22272ec8388a2c50cbfc9ca563e966be9b6469f9/src/Cedar/BridgeUnix.c#L1022):
```
[error:uninitvar][src/Cedar/BridgeUnix.c:1066]: Uninitialized variable: len
[error:uninitvar][src/Cedar/BridgeUnix.c:1056]: Uninitialized variable: i
```
> Fix some issues found with Cppcheck static analysis

- src/Mayaqua/Mayaqua.h
On uClibc, the ifaddrs.h support is optional. While the default
Buildroot uClibc configuration has it enabled, some external
toolchains may not. Therefore this patch detects that and adjusts
softether usage of ifaddrs accordingly.
Based on an initial patch from Bernd Kuhls.
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>
[Retrieved from:
https://git.buildroot.net/buildroot/tree/package/softether/0009-uclibc-ai-addrconfig.patch]
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
> Only enable getifaddrs support when available

- src/Cedar/Admin.c
Fix security issue: Fix the security of JSON-API. If the administrator password of the Virtual Hub is empty, JSON-API will not be able to access to the virtual hub with a empty password since this release. Because there are relatively many cases in which administrator password is empty for a virtual hub, being able to manage a virtual hub without a password using JSON-API was a security problem. In this release, this behavior has been changed so that JSON-API cannot be accessed in the Virtual Hub management mode until it is configured with non-empty password.
> Fix security issue: Fix the security of JSON-API

- src/Cedar/Proto_OpenVPN.c
Fixes #583.
---
From https://community.openvpn.net/openvpn/wiki/Openvpn23ManPage:
> --block-outside-dns
>
> Block DNS servers on other network adapters to prevent DNS leaks. This option prevents any application from accessing TCP or UDP port 53 except one inside the tunnel. It uses Windows Filtering Platform (WFP) and works on Windows Vista or later.
This option is considered unknown on non-Windows platforms and unsupported on Windows XP, resulting in fatal error. You may want to use --setenv opt or --ignore-unknown-option (not suitable for Windows XP) to ignore said error. Note that pushing unknown options from server does not trigger fatal errors.
> src/Cedar/Proto_OpenVPN.c: push "block-outside-dns" to clients

- src/Cedar/Proto_PPP.c
- src/Cedar/Proto_PPP.h
This is an attempt to fix up the bug #1102 .
It consists of two steps:
1. It fixes the original LCP handshake by processing LCP packets with an empty OptionsList.
2. It fixes the fallback to DHCP parsing when a static IP is rejected by processing IPCP packets without IP-Address set.
Theese fixes makes pppd under Linux be able to connect and open an IPv4 tunnel. It should be noted that by default pppd tries to configure itself statically by using IPs from its other interfaces, which gets accepted by the SoftEtherVPN's own DHCP server, but is not accepted by using any other DHCP server (in my case, DNSMasq) with meaningful settings.
Another drawback is that pppd still discards the first MS-CHAP handshake from the server because it still haven't finished the LCP handshake, but it gets …
> Fixup ppp unices

- src/Cedar/Cedar.c
- src/Cedar/Connection.c
- src/Cedar/Proto.c
- src/Cedar/Proto.h
- src/Cedar/Server.c
- src/Cedar/Server.h
The `PROTO` structure is now used to identify the system as a whole, rather than a single protocol. It's stored and initialized in `Server`.
`ProtoCompare()`, `ProtoAdd()` and `ProtoDetected()` are renamed to make the difference between `PROTO` and `PROTO_IMPL` more clear.
`ProtoGet()` and `ProtoNum()` are removed because the related list can now be accessed directly by `Server`.
> Cedar: various improvements to Proto

- src/Cedar/CedarType.h
- src/Cedar/IPC.c
- src/Cedar/Proto_L2TP.c
- src/Cedar/Proto_L2TP.h
- src/Cedar/Proto_PPP.c
- src/Cedar/Proto_PPP.h
- src/Cedar/Proto_SSTP.c
- src/Cedar/Proto_SSTP.h
- src/Mayaqua/Network.c
- src/Mayaqua/Network.h
This is an implementation of EAP-TLS protocol for the PPP stack. Yes, now you can authorize via certificates using native Windows clients too.
I've implemented the EAP stack kinda basically for now, but I hope it would be possible to expand it. Although I'm not sure what else would be needed to implement. I was thinking implementing EAP-TTLS with inner EAP protocol for secure password-based authentication (plaintext MSCHAPv2 is kinda meh), but we got either SSL of SSTP or IPsec of L2TP (noone uses plain L2TP, right?), so I guess this is already "secure enough" even with PAP...
Anyway, I've also adjusted the user policy timeouts - now they are propagating correctly in PPP-based protocols too.
Another important thing. I've added the ability to load CA certificates from the chain_certs …
> Implementation of EAP-TLS for PPP

- src/Cedar/IPC.c
- src/Cedar/Proto_PPP.c
This is a bug which I encountered with DNSMasq (which I use on my setup instead of the built-in DHCP server for a more fine-grained control).
When several clients were logging in from the same external IP (eg different computers on the same NAT network) they were all assigned the exactly same IP by DNSMasq DHCP. The debugging of this problem gave me a headache, but then after analysing DNSMasq source codes I found out that it bases it's first match of a client based on the Client_ID DHCP option.
Which was filled with the ClientHostname. Which is the same for all theese clients from the same external IP. Whoopsie.
Now I know that DNSMasq introduced an option `--dhcp-ignore-clid`, which could probably fixed this exact behaviour on it. Except that this option was introduced only in version …
> Make DHCP Client ID more unique

- src/Cedar/Proto.c
- src/Cedar/Proto.h
- src/Cedar/Proto_OpenVPN.c
- src/Cedar/Proto_OpenVPN.h
- src/Cedar/Server.c
- src/Cedar/Server.h
- src/Mayaqua/Network.c
- src/Mayaqua/Network.h
When a datagram is received, the matching session is looked up in a hash list; if it's not found, a new session is created.
This method allows to use a single UDP port for multiple protocols, as we do with TCP.
Also, each session has its own dedicated thread, used to process the received datagrams and generate the ones that are then sent through the UDP listener.
In addition to guaranteeing constant performance, separate threads also prevent a single one from blocking all sessions.
The setting that specified the UDP ports is still called `OpenVPN_UdpPortList`.
We will change it as soon as there's another UDP protocol implemented in Proto.
> Cedar: implement UDP system in Proto

- src/Cedar/Radius.h
Hello,
This PR increases by a little Radius timeout.
This to make SoftEtherVPN 2FA friendly.
Radius may be set to ask for a second authentication factor (through a push notification / validation for example), the default 10 seconds are then really short here.
15 seconds seem more reasonable to let users validate the second authentication factor.
Thank you very much for your help & support 👍
-----
Same as https://github.com/SoftEtherVPN/SoftEtherVPN_Stable/pull/7
> Increase Radius timeout

- src/Cedar/Proto.c
```
*** CID 358434: Null pointer dereferences (REVERSE_INULL)
/src/Cedar/Proto.c: 451 in ProtoHandleDatagrams()
445   void ProtoHandleDatagrams(UDPLISTENER *listener, LIST *datagrams)
446   {
447       UINT i;
448       HASH_LIST *sessions;
449       PROTO *proto = listener->Param;
450
>>>   CID 358434: Null pointer dereferences (REVERSE_INULL)
>>>   Null-checking "listener" suggests that it may be null, but it has already been dereferenced on all paths leading to the check.
451       if (proto == NULL || listener == NULL || datagrams == NULL)
452       {
453           return;
454       }
455
456       sessions = proto->Sessions;
```
> Cedar/Proto.c: fix wrong NULL check in ProtoHandleDatagrams(), found by Coverity

- src/Cedar/Protocol.c
- src/bin/hamcore/strtable_cn.stb
- src/bin/hamcore/strtable_en.stb
- src/bin/hamcore/strtable_ja.stb
- src/bin/hamcore/strtable_ko.stb
- src/bin/hamcore/strtable_pt_br.stb
- src/bin/hamcore/strtable_ru.stb
- src/bin/hamcore/strtable_tw.stb
Hello,
This PR adds the client IP in the `LH_AUTH_NG` message, the authentication failure message.
This allow to use tools such as Fail2Ban to ban IPs with too many authentication failures / retries.
Thank you very much for your help & support 👍
-----
Same as https://github.com/SoftEtherVPN/SoftEtherVPN_Stable/pull/8
> Log client IP in failed accesses

- src/Cedar/IPC.c
Fixes as per review of @chipitsine (https://github.com/SoftEtherVPN/SoftEtherVPN/pull/1125#issuecomment-630783928)
They are not fatal (nothing will break because of it) but they are errors, so they should be fixed =)
Theese are actually minimal:
1. Wrong source IP used when requesting the server EUI (should had been a link-local address generated using the Client EUI, instead it was just using an unitialized variable)
2. A break statement missing which could cause addition of a TargetLinkLayer to a Neighbor Solicitation request (which doesn't make sense).
> Fixes from review of PPP-IPv6 stack

- src/Mayaqua/TcpIp.c
- Fixed the problem that BuildDhcpOptionsBuf could not interpret the option size correctly because NewDhcpOption truncated the option size to 8bit.
This causes problems when the virtual DHCP server has more than 28 static routes defined.
(It may not be necessary to remove the cast on id.)
---
Fixes #326.
> Fixed that NewDhcpOption can't handle DHCP options longer than 255 bytes

- src/Cedar/Server.c
Unfortunately I realized only now that I didn't add the code in #1130.
> Cedar/Server.c: load UDP ports from configuration file and apply them

- src/Cedar/Server.c
I accidentally passed the wrong variable in 4514ba5e2f597b3ecbedda2eee48bebf8ae693fe.
> Cedar: fix ProtoSetUdpPorts() call in SiLoadServerCfg()

- src/Cedar/Session.c
`ClientOption`, as the name implies, is only used in a client context.
The issue was introduced in #1157. Before that, an unrelated check prevented `UnixVLanSetState()` from being called in a server context.
> Cedar: fix server crash in CleanupSession()

- src/Mayaqua/Internat.c
- src/Mayaqua/Internat.h
- src/Mayaqua/Str.c
`strtok()` and `wcstok()` are considered unsafe functions.
A segmentation fault caused by the use of `strtok()` was recently reported: #975
>  Remove all references to strtok() and wcstok(), implement and use alternatives

- .appveyor.yml
- .ci/azure-pipelines-linux.yml
- .ci/azure-pipelines-win.yml
- .ci/sonarcloud.sh
- .cirrus.yml
- .gitlab-ci.yml
- .travis.yml
- CMakeLists.txt
- configure
- configure.cmd
- src/hamcorebuilder/CMakeLists.txt
- src/vpnbridge/CMakeLists.txt
- src/vpnclient/CMakeLists.txt
- src/vpncmd/CMakeLists.txt
- src/vpncmgr/CMakeLists.txt
- src/vpnserver/CMakeLists.txt
- src/vpnsmgr/CMakeLists.txt
- src/vpntest/CMakeLists.txt
Our CMake project used to forcefully create and use two different build directories: `build` and `tmp`.
This commit changes the behavior so that only the build directory CMake is ran in is used.
> CMake: don't hardcode build directories

- src/vpnbridge/CMakeLists.txt
- src/vpnclient/CMakeLists.txt
- src/vpncmd/CMakeLists.txt
- src/vpnserver/CMakeLists.txt
When `VPN_EXE` is defined, Mayaqua.h defines `WinMain()`, which handles arguments in a special way.
This commit passes `WIN32` to `add_executable()`, so that `WinMain()` is used as entry point instead of `main()`.
The use of `main()` instead of `WinMain()` was causing service mode not to work due to the `/service` argument being discarded.
`vpntest` is not a service, but for consistency we specify `WIN32` for it as well because it defines `VPN_EXE`.
> CMake: specify "WIN32" for targets that have WinMain(), add manifest for all targets that have it in the MSBuild project

- src/vpntest/vpntest.c
> vpntest.c: add "setupapi" command to test SetupAPI (Windows only)

- src/Cedar/Proto.c
- src/Cedar/Proto.h
- src/Cedar/Proto_OpenVPN.c
- src/bin/hamcore/strtable_cn.stb
- src/bin/hamcore/strtable_en.stb
- src/bin/hamcore/strtable_ja.stb
- src/bin/hamcore/strtable_ko.stb
- src/bin/hamcore/strtable_pt_br.stb
- src/bin/hamcore/strtable_ru.stb
- src/bin/hamcore/strtable_tw.stb
Example of the new messages:
```
[OpenVPN] 192.168.122.100:47390 -> 0.0.0.0:1194 (UDP): Session created.
[OpenVPN] 192.168.122.100:47390 -> 0.0.0.0:1194 (UDP): Session deleted.
[OpenVPN] 192.168.122.100:49866 -> 192.168.122.1:1194 (TCP): Session created.
[OpenVPN] 192.168.122.100:49866 -> 192.168.122.1:1194 (TCP): Session deleted.
```
Example of the redundant messages (now removed):
```
OpenVPN Module: The OpenVPN Server Module is starting.
OpenVPN Session 1 (192.168.122.211:47390 -> 0.0.0.0:1194): A new session is created. Protocol: UDP
OpenVPN Session 1 (192.168.122.211:47390 -> 0.0.0.0:1194): Deleting the session.
OpenVPN Module: The OpenVPN Server Module is stopped.
```
> Proto: write message to log on session creation/deletion, remove redundant OpenVPN messages

- developer_tools/vpnserver-jsonrpc-clients/README.html
- developer_tools/vpnserver-jsonrpc-clients/README.md
Fix the packet count and bytes descriptions being mismatched in the JSON-RPC documentation.
For example the description for `Recv.BroadcastBytes_u64` should be 'Broadcast bytes (Recv)' instead of 'Number of broadcast packets (Recv)' in the sections 'GetServerStatus', 'SetHubOnline', 'CreateUser', 'SetUser', 'GetUser', 'CreateGroup', 'SetGroup' and 'GetGroup'.
> Fix Parameter Descriptions in the JSON-RPC Documentation

- src/BuildUtil/VpnBuilder.cs
- When building on Windows XP using Visual Studio 2008, I encountered the following issue.
- I did a fresh install of Windows XP SP3 32-bit, then applied updates including .NET 3.5. Next I installed MS Visual Studio 2008, then updated with sp1. All of this according to the documentation in your readme for building on Windows.
- In file src/BuildUtils/VpnBuilder.cs, there are two "if" statements testing the same thing, which is to determine if it is a 32-bit or 64-bit machine/compiler. But the then and else clauses are reversed, so clearly, one of them is wrong. The result I saw is that the SDK path being used to run RC.exe is left as the NULL string and so it fails to run the RC.exe program.
- This happens early in the build process, building the …
> BuildUtil: fix an issue encountered with Visual Studio 2008 on Windows XP

- .travis.yml
rpath is more elegant way of linking libraries. maybe, we'll write a guide "how to install custom openssl and link against it"
> travis-ci: do not use aggressive LD_LIBRARY_PATH anymore

- AUTHORS.TXT
- src/Cedar/Account.c
- src/Cedar/Account.h
- src/Cedar/Session.c
- src/Cedar/Session.h
- src/Cedar/Virtual.c
- src/Cedar/Virtual.h
Feature proposed in this pull request:
assigning a static IP address to the user by the internal DHCP server.
It is independent of the client software.
How it works:
A)  in the SessionMain() function: 
1) check incomming frames 
2) for DHCPDISCOVER and DHCPREQUEST frames, write down the static IP address 
( which is readed form user's note ) in the SIADDR field of the DHCPHEADER
3) process the modified frame like the others
B) in the VirtualDhcpServer() function:
- for the DHCPDISCOVER and DHCPREQUEST frames, read the static IP address 
from the SIADDR field of the DHCPHEADER and treat it as the required IP address
> Cedar: DHCP server now assigns static IPv4 address, if present in user note

- README.md
This pull request:
- Replaces the broken GitLab CI badge link (reference: https://docs.gitlab.com/ee/ci/pipelines/settings.html#pipeline-status-badge).
- Adds the Azure Pipelines badge for the Nightly pipeline.
- Adds the Cirrus CI badge.
- Rearranges the badges in a table.
> README.md: update build status badges

- src/Cedar/Server.c
- src/Mayaqua/Network.c
- src/Mayaqua/Network.h
Add Tls_Disable1_3 like Tls_Disable1_2 etc.
This change is part of v4.34-9744-beta 
https://github.com/SoftEtherVPN/SoftEtherVPN_Stable/commit/e3370fb62c31eb10d0d221e628161863358d4cc3 .
Ref #1110 .
Is this kind of backport PR accepted?
> Add Tls_Disable1_3 (Import v4 change)

- src/Cedar/Session.c
> Cedar/Session.c: fix "use after free" in CleanupSession()

- src/Cedar/Connection.c
To solve the problem that the escape condition of the loop that tries name resolution in UDP mode was reversed in the keep-alive function of the Internet connection, so the name resolution retry is set to 250 msec interval instead of the normal 60 second interval.
> Fixed setting change trigger of keepalive function

- src/BUILD_UNIX.md
Ruby-based Homebrew installer is deprecated by original authors, and replaced Bash-based Installer.
(ref1: https://github.com/Homebrew/install/blob/master/README.md )
(ref2: https://github.com/Homebrew/install/commit/26806377779aedfddcb1f0cbdf1416e865b9750a#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5 )
note: /Homebrew/install/master/install also runs Bash-based installer now.
> update Install requirements on macOS

- src/Cedar/SM.c
Issue: https://github.com/SoftEtherVPN/SoftEtherVPN/issues/1247
> Bug fix: Proxy button not enabled for SOCKS5

- src/Cedar/Proto.c
The bug was introduced in #1177.
> Cedar/Proto.c: fix crash in ProtoHandleConnection()

- src/Mayaqua/Network.c
OPENSSL_VERSION is fragile in LibreSSL, BoringSSL.
security level manipulation is openssl specific defined in
https://github.com/openssl/openssl/commit/b362ccab5c1d52086f19d29a32f4acc11073b86b
> use SSL_SECOP_VERSION macro instead of OPENSSL_VERSION

- version.py
```python
File "version.py", line 25
print(version, end = end)
^
SyntaxError: invalid syntax
```
> version.py: Fix CI failure on macOS by avoiding inline if statement

- .ci/azure-pipelines/macos_build.sh
- version.py
#1271 was not the solution, the error is the print statement itself.
Python 2 is probably used by default and thus `python` is an alias to it.
> Azure Pipelines: Use "python3" instead of "python" on macOS, restore inline if statement in version.py

- src/Mayaqua/Unix.c
(gdb) bt
```
0  0x00007f43857a5e14 in __GI___pthread_mutex_init (mutex=0x0, mutexattr=0x0) at pthread_mutex_init.c:89
1  0x00007f4385eaaf1b in UnixNewLock () at SoftEtherVPN/src/Mayaqua/Unix.c:1845
2  0x00007f4385e92331 in NewLockMain () at SoftEtherVPN/src/Mayaqua/Object.c:89
3  0x00007f4385e92359 in NewLock () at SoftEtherVPN/src/Mayaqua/Object.c:101
4  0x00007f4385e92765 in NewCounter () at SoftEtherVPN/src/Mayaqua/Object.c:171
5  0x00007f4385e92e76 in NewRef () at SoftEtherVPN/src/Mayaqua/Object.c:339
6  0x00007f4385e76939 in NewSkEx (no_compact=0) at SoftEtherVPN/src/Mayaqua/Memory.c:863
7  0x00007f4385e68c95 in NormalizePathW (
dst=0x7ffe65932940 L"\xd6ff2ffb\xfbf14ce5\xad8669ca\x41998a9c\x5107d62d\x8d2ab3f2\x37ceaad2\xffc947ec\xad8ed8d8\x33e9f2f7\xc05723a9\x843263e3\x5516beb3\x12571 …
```
> fix null pointer dereference found by ErrorSanitizer

- src/hamcorebuilder/main.c
`FileClose()` was not called if `FileRead()` failed.
> hamcorebuilder: Fix possible resource leak found by Coverity

- src/CMakeLists.txt
Previously, the file was rebuilt even if no changes were made to the source files.
> CMake: Build hamcore.se2 only when related files change

- src/Cedar/CMakeLists.txt
- src/Cedar/Win32Com.h
- src/Cedar/WinJumpList.cpp
- src/Mayaqua/CMakeLists.txt
- src/Mayaqua/Mayaqua.h
- src/vpninstall/vpninstall.c
- src/vpnweb/vpnwebdlg.c
In addition to making the code cleaner, this also prevents potential issues due to `#pragma` directives being in headers.
> Link to Windows libraries in CMake project, remove related #pragma directives

- src/Cedar/WinUi.c
> Cedar/WinUi.c: Remove reference to "vpncmd_x64.exe" and "vpncmd_ia64.exe"

- src/Mayaqua/Network.c
This bug was originally reported by crow31415 on VPN User Forum.
https://www.vpnusers.com/viewtopic.php?f=15&p=93014
```
Client (172.20.x.x) --- (Internet) --- Reverse proxy (port 443) --- (forwards to 127.0.0.1:5555) --- SE server (port 5555)
|----------                    server                    -----------|
```
A reverse proxy (sslh) has been set up on the server for multiplexing.
From the server's point of view, the session is a local one (from 127.0.0.1 to 127.0.0.1). So it creates UDP socket at 127.0.0.1:40000. However, the client who is not aware of the reverse proxy puts its local IP (172.20.x.x) in the authentication message.
Later when the server tries to send UDP packets to that address (127.0.0.1 -> 172.20.x.x), SendToEx reports EINVAL (22) error, which is not captured by …
> Mayaqua: Fix UDP send error when used with reverse proxy

- src/Mayaqua/Network.c
`O_NONBLOCK` is standardized by POSIX, as opposed to `FIONBIO`.
This commit also fixes a bug: `fcntl()` was only called to disable the mode.
> Mayaqua/Network.c: Always use fcntl() to toggle socket non-blocking mode (UNIX)

- src/Cedar/Admin.c
- src/Cedar/CM.c
- src/Cedar/Client.c
- src/Cedar/EM.c
- src/Cedar/Hub.c
- src/Cedar/IPC.c
- src/Cedar/NativeStack.c
- src/Cedar/Proto.c
- src/Cedar/Proto_IKE.c
- src/Cedar/Proto_IkePacket.c
- src/Cedar/Proto_OpenVPN.c
- src/Cedar/Proto_Win7.c
- src/Cedar/Protocol.c
- src/Cedar/SM.c
- src/Cedar/Virtual.c
- src/Cedar/WinUi.c
- src/Mayaqua/Network.c
- src/Mayaqua/Network.h
- src/Mayaqua/Pack.c
- src/Mayaqua/Proxy.c
- src/Mayaqua/TcpIp.c
In addition to saving 4 bytes for each instantiation, this change makes IP-related operations faster and clearer.
https://tools.ietf.org/html/rfc3493.html#section-3.7
> Change IP structure so that IPv4 addresses are stored in RFC3493 format

- src/Cedar/Connection.c
- src/Cedar/Protocol.c
- src/Cedar/UdpAccel.c
- src/Cedar/UdpAccel.h
Before this commit, the IP address reported by the NAT-T server was immediately discarded.
That's because the peer should be accessible via the IP address used to establish the TCP connection.
User @domosekai (https://www.domosekai.com) pointed out that the NAT-T IP address should be taken into account.
In his case it's required due to his broadband carrier's NAT causing TCP and UDP to have different external IPs.
> Cedar: Make use of IP address reported by NAT-T server for UDP acceleration

- .appveyor.yml
since https://github.com/OpenVPN/openvpn/commit/24596b258aa3a9c0bd79e7e7bd4753c48a435408
bundled lz4 was removed. openvpn (used for live tests) now relies on system
lz4 lib.
> CI: AppVeyor: explicitly install liblz4-dev

- .ci/azure-pipelines/linux.yml
since https://github.com/OpenVPN/openvpn/commit/24596b258aa3a9c0bd79e7e7bd4753c48a435408
bundled lz4 was removed. openvpn (used for live tests) now relies on system lz4 lib.
> CI: Azure Pipelines: explicitly install liblz4-dev

- src/Cedar/Connection.c
- src/Cedar/Hub.c
- src/Cedar/Logging.c
- src/Cedar/Protocol.c
- src/Cedar/Radius.c
- src/Cedar/Server.c
- src/Cedar/UdpAccel.c
- src/Cedar/Virtual.c
- src/Cedar/Wpc.c
- src/Mayaqua/DNS.c
- src/Mayaqua/DNS.h
- src/Mayaqua/MayaType.h
- src/Mayaqua/Network.c
- src/Mayaqua/Network.h
- src/Mayaqua/Proxy.c
- src/Mayaqua/Table.c
From a functional point of view, the main improvement is that `GetIP()` now always prioritizes IPv6 over IPv4.
The previous implementation always returned an IPv4 address, unless not available: in such case it failed.
This means that now connections to hostnames should be established via IPv6 if available.
From a programmer point of view, getting rid of the insane wrappers is enough to justify a complete rewrite.
As an extra, several unrelated unused global variables are removed.
> Rewrite DNS API from scratch into dedicated file(s)

- src/Cedar/Admin.c
- src/Cedar/Command.c
- src/Cedar/Proto.c
- src/Cedar/Proto.h
- src/Cedar/Proto_OpenVPN.c
- src/Cedar/Proto_OpenVPN.h
- src/Cedar/Server.c
- src/bin/hamcore/strtable_cn.stb
- src/bin/hamcore/strtable_en.stb
- src/bin/hamcore/strtable_ja.stb
- src/bin/hamcore/strtable_ko.stb
- src/bin/hamcore/strtable_pt_br.stb
- src/bin/hamcore/strtable_ru.stb
- src/bin/hamcore/strtable_tw.stb
Also, the default timeout value is set to 30000 (milliseconds) instead of 10000.
The change is made because it was reported that some routers failed to connect in time: #495
---
This PR also fixes a bug which caused the server to initialize all boolean options to false.
It was caused by `SiLoadProtoCfg()` not checking whether the item exists in the configuration file.
`CfgGetBool()` always returns false if the item doesn't exist.
> Cedar: Make OpenVPN timeout and ping transmission interval configurable

- src/Mayaqua/TcpIp.c
src/Mayaqua/TcpIp.c	1811	warn	V560 A part of conditional expression is always false: udp->Checksum == 0.
> src/Mayaqua/TcpIp.c: remove redundant check

- src/Cedar/IPC.c
Per RFC 1112, Ethernet multicast address should be in the form of 01-00-5E-00-00-00, where the lowest 23 bits are copied from the destination IP.
Since multicast is currently treated as broadcast, this commit does not actually fix anything but may help reducing broadcast traffic.
---
- Change destination MAC address for IPv4 multicast per RFC 1112
> Cedar/IPC: Fix MAC address for IPv4 multicast

- src/Mayaqua/Network.c
SecureNAT is IPv4 only however it gets the default DNS server from the first nameserver in `resolv.conf` which might not always be IPv4.
For example, Vultr hosts have IPv6 DNS before IPv4 in the file, causing DNS lookup to fail.
```
root@vultr:~/SoftEtherVPN/build# cat /etc/resolv.conf
nameserver 2001:19f0:300:1704::6
nameserver 108.61.10.10
```
`GetDefaultDns()` is only used in SecureNAT so the change should be safe.
---
- Skip IPv6 nameservers in resolv.conf for SecureNAT
> Mayaqua/Network: Skip IPv6 nameservers for SecureNAT

- src/Cedar/BridgeUnix.c
- src/Mayaqua/DNS.c
- src/Mayaqua/Network.h
- `<pthread.h>` included for the `pthread_t` type definition.
- `<net/ethernet.h>` include removed as the header doesn't exist.
- `AI_ALL` and `AI_V4MAPPED` defined to 0 as the options don't exist.
> Fix compile errors on OpenBSD

- src/Cedar/Proto_PPP.c
When the peer sends a fragmented EAP-TLS packet, we should respond with an empty TLS data packet which serves as an ACK.
However, the response should still carry a flag octet which the current implementation forgets to do.
To be intuitive, the correct ACK packet looks like this (in PPP payload):
```
01 05 00 06 0d 00
|  |  |     |  |
|  id len   |  flag
request     tls
```
Currently it look like this:
```
01 05 00 05 0d
```
This bug only occurs when client certificate is large enough to trigger fragmentation, causing Win 10 client to fail.
---    
- Fix EAP-TLS fragmentation handling
> Cedar/Proto_PPP: Fix EAP-TLS fragmentation

- CMakeLists.txt
See also: https://github.com/SoftEtherVPN/SoftEtherVPN/issues/1392#issuecomment-867348281
> Add warning about build number, initialize to 5180

- src/Cedar/Admin.c
- src/bin/hamcore/strtable_cn.stb
- src/bin/hamcore/strtable_en.stb
- src/bin/hamcore/strtable_ja.stb
- src/bin/hamcore/strtable_ko.stb
- src/bin/hamcore/strtable_pt_br.stb
- src/bin/hamcore/strtable_ru.stb
- src/bin/hamcore/strtable_tw.stb
Turns out `%S` refers to ANSI/UTF-8 and `%s` to UTF-16.
This commit fixes a buffer overflow reported by AddressSanitizer and removes an unnecessary conversion to UTF-16.
> Use "%S" instead of "%s" for LA_SET_PORTS_UDP and LA_SET_PROTO_OPTIONS

- src/Cedar/Admin.c
- src/Cedar/SM.c
- src/Cedar/Sam.c
- src/Cedar/Wpc.c
- src/Cedar/Wpc.h
- src/Mayaqua/CMakeLists.txt
- src/Mayaqua/Cfg.c
- src/Mayaqua/Encoding.c
- src/Mayaqua/Encoding.h
- src/Mayaqua/Memory.c
- src/Mayaqua/Memory.h
- src/Mayaqua/Pack.c
- src/Mayaqua/Proxy.c
- src/Mayaqua/Str.c
Our own implementation works fine, however we should use OpenSSL's one since we already link to the library.
`Base64Decode()` and `Base64Encode()` return the required buffer size when `dst` is `NULL`.
This allows to efficiently allocate a buffer, without wasting memory or risking an overflow.
`Base64FromBin()` and `Base64ToBin()` perform all steps, returning a heap-allocated buffer with the data in it.
> Refactor Base64 functions, encode/decode using OpenSSL's EVP interface

- README.md
Now that SoftEther officially support WireGuard, it can also be mentioned on the README page.
related to #1296
> Add WireGuard mention to README.md

- src/Cedar/Connection.c
Fixing buffer overflow reported by @chipitsine.
When we insert both NAT-T IP and port in the keep-alive packets, the minimum size should be the total length of the two items but we are currently using the larger of the two.
---
- Fix buffer overflow when inserting NAT-T information
> Cedar/Connection.c: Fix buffer overflow when inserting NAT-T information

- src/Cedar/Protocol.c
Currently when the client sends node info to the server, server IP is resolved again where the result may not be the actual one being used.
This is unnecessary in direct mode at least and may result in reporting incorrect server addresses.
---
- Use real server IP in node info under direct connection
> Cedar/Protocol.c: Use real server IP in creating node info under direct mode

- src/Mayaqua/DNS.c
Fix an issue that if both IPv6 and IPv4 addresses are resolved, IPv4 ones may not be saved or used at all.
---
- Fix DNS resolution in dual stack environment
> Mayaqua/DNS.c: Fix DNS resolution in dual stack environment

- src/Mayaqua/Network.c
Before https://github.com/SoftEtherVPN/SoftEtherVPN/commit/914bfe7d44f8e693d21178055f0b845c613dc777, we defined our `bool` type as `int` and used it indifferently both internally and in socket options.
Now that we are using C99 `bool`, socket options needed to be explicitly set in `int`.
This fix restores TCP listeners in IPv6.
Close #1413
---
- Use int type socket options as our bool type has changed
> Mayaqua/Network.c: Use int as boolean flags for socket options

- src/Cedar/CMakeLists.txt
- src/Cedar/Command.c
- src/Cedar/Command.h
- src/Mayaqua/CMakeLists.txt
- src/Mayaqua/Crypto/Key.c
- src/Mayaqua/Crypto/Key.h
- src/Mayaqua/Crypto/Types.h
- src/Mayaqua/MayaType.h
- src/PenCore/CMakeLists.txt
- src/bin/hamcore/strtable_cn.stb
- src/bin/hamcore/strtable_en.stb
- src/bin/hamcore/strtable_ja.stb
- src/bin/hamcore/strtable_ko.stb
- src/bin/hamcore/strtable_pt_br.stb
- src/bin/hamcore/strtable_ru.stb
- src/bin/hamcore/strtable_tw.stb
- src/vpnbridge/CMakeLists.txt
- src/vpnclient/CMakeLists.txt
- src/vpncmd/CMakeLists.txt
- src/vpncmgr/CMakeLists.txt
- src/vpnserver/CMakeLists.txt
- src/vpnsetup/CMakeLists.txt
- src/vpnsmgr/CMakeLists.txt
- src/vpntest/CMakeLists.txt
```
VPN Tools>GenX25519
GenX25519 command - Create new X25519 keypair
Private key: yH1560qrKTC17VRDxvhrz90WjMn2YpyxbPXkSH1OknM=
Public key: vpiJEOy7KYzZjbMNb9ycGJJzOFST6Y3pToWRKHTMOFw=
The command completed successfully.
VPN Tools>GetPublicX25519
GetPublicX25519 command - Retrieve public X25519 key from a private one
Private key: yH1560qrKTC17VRDxvhrz90WjMn2YpyxbPXkSH1OknM=
Public key: vpiJEOy7KYzZjbMNb9ycGJJzOFST6Y3pToWRKHTMOFw=
The command completed successfully.
VPN Tools>GetPublicX25519 yH1560qrKTC17VRDxvhrz90WjMn2YpyxbPXkSH1OknM=
GetPublicX25519 command - Retrieve public X25519 key from a private one
Public key: vpiJEOy7KYzZjbMNb9ycGJJzOFST6Y3pToWRKHTMOFw=
The command completed successfully.
VPN Tools>
```
---
```
GenX25519 command - Create new X25519 keypair
Help for command …
```
> Cedar/Command: Add GenX25519 and GetPublicX25519 commands

- src/Cedar/Listener.c
- src/Mayaqua/Network.c
- src/Mayaqua/Network.h
The listener function currently has these problems.
- TCP listener does not observe IPv6 `ListenIP`
- TCP listener always listens on `::` even `ListenIP` is set to a specific value
- UDP listener can't listen on both `0.0.0.0` and `::`
- L2TP/IPsec not working over IPv4 with default `ListenIP` config on dual-stack server
This commit proposes these changes.
- Add ListenIP support to TCP listener in IPv6
- When ListenIP is set to either `0.0.0.0` or `::`, we will listen on the other address as well
This special treatment is proposed due to backward compatibility consideration. (see below)
Now the problems above should be solved.
1. Backward compatibility
At first I thought that we should treat `ListenIP 0.0.0.0` as IPv4 only and `ListenIP ::` as IPv6 only. If `ListenIP` is not present in …
> Fix TCP and UDP listener behavior

- src/Mayaqua/Network.c
Currently L2TP/IPsec connects over IPv6 only if the server listens on some interface. It does not work if `ListenIP` is `::`.
The probable reason is that zero IP with special ports (used by ESP, for example) are skipped in the listener thread.
I have tested on Win 10 client and now it works. However I am not sure why there is such check. Please correct me if it's improper.
Stable version does not have the issue since it creates listeners on every interface.
---
- Comment out checking zero IP with special ports to restore L2TP/IPsec connectivity over IPv6
> Mayaqua/Network.c: Fix L2TP/IPsec over IPv6 when listening on ::

- src/Cedar/Proto_L2TP.c
- src/Cedar/Proto_L2TP.h
- src/Cedar/Proto_PPP.c
- src/Cedar/Proto_PPP.h
- src/Cedar/Proto_SSTP.c
- src/Cedar/Proto_SSTP.h
- src/Mayaqua/Network.c
- src/Mayaqua/Network.h
When a L2TP or SSTP session is terminated, use-after-free problem occurs very often, due to a insecure access to `DataTimeout` of a `PPP_SESSION` object.
This issue was introduced in https://github.com/SoftEtherVPN/SoftEtherVPN/commit/1bdd9a92bcd97b55d0863a01202d872e16c4b32d .
Before that commit, L2TP and SSTP sessions do not retain reference of `PPP_SESSION` directly because it is freed in Proto_PPP.
But in order to access the timeout value of the PPP session, a reference is retained and accessed in the interrupt process function.
Since the `PPPSession` object gets freed elsewhere, the current nullity check is useless:
https://github.com/SoftEtherVPN/SoftEtherVPN/blob/a2f30c8aadb544ff02a3eaaeb5dc7e4b518481b1/src/Cedar/Proto_SSTP.c#L447-L450
This fix reverts the practice and save the …
> Fix use-after-free timeout issue for L2TP and SSTP

- src/Cedar/Proto_PPP.c
- src/Cedar/Proto_PPP.h
- src/Cedar/Radius.c
Currently Windows built-in SSTP and L2TP client cannot connect out of the box because our EAP implementation only supports certificates.
This PR adds EAP-MSCHAPv2 password support and an ordinary user can connect without any hassle now.
The only thing I am not sure is double MSCHAPv2, apparently used in RADIUS. 
Edited: I did it in the second commit but I have no RADIUS environment to test. 
Tested with Win 10, Android SSTP Client, and of course, **iOS SSTP Connect**. 😁
Fix #1169
Fix #1253
---
- Implement EAP-MSCHAPv2
> Implement EAP-MSCHAPv2

- src/Mayaqua/Network.c
Due to the fact that one UDP socket is handling multiple sessions, if the bind address is wildcard, we can't get the actual local address as in TCP. Therefore the return packet's source address will be determined by the routing table. 
It usually works fine but may have issues in multi-interface environment. That is to say, a return packet may have source address different with the destination of the incoming packet, leading to problem in policy-based routing.
This might be one reason why the original version (before the introduction of `ListenIP`) binds UDP listener on every interface but TCP on wildcard only. (Yeah there must be a reason...)
This PR restores the orginal behavior if `ListenIP` is either `0.0.0.0` or `::`. 
Also the fix in #1417 is no longer needed and thus reverted. …
> Mayaqua/Network.c: Create UDP listener for every interface if ListenIP is wildcard

- src/Cedar/IPC.c
Many of you might have noticed that since the implementation of Wireguard, the server cannot exit normally sometimes.
It turns out that the issue is not directly related to Wireguard, but due to a hub reference not released in `NewIPC()`. It affects all protocols that use IPC.
#1307
---
- Fix hub release in NewIPC()
> Cedar/IPC.c: Add hub release in NewIPC()

- src/Mayaqua/TcpIp.c
Fix wire format of DHCP Classless Route Option after the refactor of IP.
Address #1399
---
- Fix wire format of DHCP Classless Route Option
> Mayaqua/TcpIp.c: Fix building DHCP static routes in new format

- src/Mayaqua/Network.c
As discussed in https://github.com/SoftEtherVPN/SoftEtherVPN/issues/1436 , there is race condition between the two ends of a `TUBE` object.
One end sends an IPC packet to tube and flushes it:
https://github.com/SoftEtherVPN/SoftEtherVPN/blob/bf14817f1f09f8b8107b13add08f483ad99abb7c/src/Cedar/Connection.c#L1295-L1313
The flush operation races with the receive end (OpenVPN server) calling `IPCSetSockEventWhenRecvL2Packet` and eventually `SetTubeSockEvent`.
https://github.com/SoftEtherVPN/SoftEtherVPN/blob/bf14817f1f09f8b8107b13add08f483ad99abb7c/src/Cedar/Proto_OpenVPN.c#L2530-L2542
There is tube locking mechanism in `SetTubeSockEvent` but not in `TubeSendEx2` and `TubeFlushEx`.
---
- Fix race condition in TUBE operation
> Mayaqua/Network.c: Fix race condition in TUBE operation

- src/Mayaqua/CMakeLists.txt
We need the function since #1415, but unfortunately it's not provided by LibreSSL.
By introducing a build time check we inform the user about the issue explicitly instead of just letting compilation fail.
This is a replacement for #1421.
> CMake: Add build time check for EVP_PKEY_get_raw_public_key() availability

- CMakeLists.txt
@davidebeatrici , can you have a look please ?
this "works for me", however, I'm not sure I'm following best practices. I'm bit lost in various rpath/runpath options of CMake
> BUILD: use rpath for locating dynamic libraries

- src/Cedar/Protocol.c
- Fixed an issue where changing the password from the client did not increment the revision of the server config file and the changes were not saved
https://www.vpnusers.com/viewtopic.php?f=15&t=67107
> Password change from client increments config file revision

- src/Cedar/CM.c
- src/Cedar/Client.c
Now Windows client manager properly refreshes when connection status changes, new adapter is added etc.
It seems to also fix #1444, which is unexpected.
> Fix auto refreshing of client manager

- src/Cedar/Account.c
- src/Cedar/Account.h
- src/Cedar/Admin.c
When I saw #1488 , I did a test on my server and found that policy setting are not working.
Yet another bug after the bool refactor (#1282) .
I tried to avoid changing each usage of these macros. Not sure if there is a better way.
> Fix policy dialog and memory overrun

- src/Cedar/Proto_PPP.c
IPC DHCP leases are not renewed properly due to a bug in the PPP thread.
The time tick saved in `now` is not updated, causing renewal checkpoints never reachable.
Fix #1262
Fix #1302
> Cedar/Proto_PPP: Fix IPC DHCP renewal

- src/Cedar/Server.c
Hub option `NoIPv6DefaultRouterInRAWhenIPv6` controls whether the remote IPv6 default route is honored when the connection is made via IPv6. 
Since we didn't manage IPv6 routes in Client Manager before #1443, this option is defaulted to true to prevent the accidental override of the local IPv6 routes by the remote ones.
And now we have the feature, it's time to revert the default value to false, in order to allow remote IPv6 gateways to work. 
Otherwise users may find it strange that they can't route Internet traffic over IPv6 in the same way as IPv4.
Fix #1163
> Change default hub option to allow default router in IPv6 RA

- src/Mayaqua/Network.c
As @Evengard said in #1109, for client certificates with CAs other than the server CA to work, one must manually add them to `chain_certs`.
Since `chain_certs` is supposed to contain server's trust chain, it doesn't make sense to put client CAs there. This approach is just a hack and may confuse many users.
Without the hack, server can't get client certificate from EAP-TLS process to continue its internal authentication. So I digged a little bit to understand why.
It turns out that only in TLS verification callbacks with `preverify_ok` being true we save the client certificate. 
Without trusting client CA beforehand, `preverify_ok` is never true and client certificate is never saved.
Since the callback is a pass-through which does not perform actual verification, I changed it to save …
> Mayaqua/Network.c: Fix EAP-TLS chain certificate verification

- src/Mayaqua/DNS.c
- src/Mayaqua/Network.c
- src/Mayaqua/Network.h
Our current DNS resolver requests IPv4-mapped IPv6 addresses from the system resolver. It aims to get both IPv4 and IPv6 addresses in a single run. 
However on hosts where no IPv6 address is configured (including local unicast addresses), IPv4 results will not be returned due to flag option `AI_ADDRCONFIG`.
This PR detects the existence of IPv6 addresses and requests IPv4 result only if not detected.
Fix #1428
> Fix DNS resolution when no IPv6 address is configured on any interface

- src/Mayaqua/Network.c
NAT traversal is not functioning on the server because the default ListenIP is :: (IPv6) but NATT server is IPv4 only.
This PR fixes it.
> Restore R-UDP listener when ListenIP is ::

- src/Cedar/Command.c
- src/Cedar/SM.c
- src/Mayaqua/Network.c
`IPToUINT(IP*)` is supposed to work on IPv4 addresses only but currently does not check the type of the input address. This leads to random outcome on IPv6 input and corrupts session info display like the one below.
```
Item                                      |Value
------------------------------------------+-------------------------------------------------------------
Client IP Address                         |61.84.206.189
Client Host Name                          |2600:1f13:559:8f00:6604:c537:3d54:cebd
```
This PR fixes both vpncmd and the server manager.
> Fix IPv6 address display in session info dialog

- src/Mayaqua/DNS.c
- src/Mayaqua/DNS.h
- src/Mayaqua/Network.c
In #1329 , @davidebeatrici  refactored the DNS threads but it didn't change the fact that the threads are still asynchronous. 
In #1512 , I enriched the DNS resolver to return a list of addresses. 
Probably both Davide and I assumed that the resolver thread is synchronous. **We were wrong.**
https://github.com/SoftEtherVPN/SoftEtherVPN/blob/2f801f30de646e2dbe66f3661535a7cb7e797041/src/Mayaqua/DNS.c#L333-L363
After timeout, the caller continues and gets released but the resolver thread may still be running. If it ends up with successful result, the resolver will save the addresses in memory released already.
Therefore parameters `DNS_RESOLVER` can't be created as value in the caller. Basically this reverts to the treatment before the refactor. 
This fixes a typo in #1512. @chipitsine …
> Fix DNS thread safety and other

- src/Cedar/SM.c
When user regenerates server certificates from the Server Manager, `chain` is not initialized because the regeneration function does not offer a chain, causing uninitialized `chain` be used.
Fix #1433
> Cedar/SM.c: Fix pointer usage before initialization

- src/Cedar/Connection.h
- src/Cedar/SM.c
- src/Cedar/SMInner.h
- src/Cedar/Wpc.h
- src/Mayaqua/Proxy.h
As mentioned in #1535 , since 5.01 build 9658 we have accidentally diverted from the original format (for 3 times) used to save server manager settings in the Windows registry. 
This PR restores the compatibility with the original format and automatically convert three diverted formats when loading from the registry. 
This should eliminate any data loss no matter what version the user is upgrading from.
Close #1535
> Fix server manager setting compatibility since build 9658

- src/Mayaqua/Network.h
Missing argument check lead to wrong value of IsIPv6 of struct UDP_ACCEL in NewUdpAccel(),  eventually lead to UdpAccelInitClient() fail.
- 
- 
-
> Mayaqua/Network.h: Fix UDP acceleration under NAT-T connections

- src/Cedar/BridgeUnix.c
- src/Cedar/VLanUnix.c
- src/Mayaqua/Unix.c
A recent refactor removed a number of headers required on solaris/illumos systems. This patch adds those headers back. 
See https://gitlab.com/SoftEther/SoftEtherVPN/-/jobs/1818748494 for details of (one of) the missing definitions.
> Add missing headers required for solaris/illumos

- README.md
The AzureDevOps would be a very useful link/info to include I think, or is there some reason not to?
Also a small suggestion to clarify what can actually be found at softether-download.com (stable channel)
> Readme - add info for Windows & macOS nightlies

- src/Cedar/Admin.c
- src/Mayaqua/Memory.c
- src/Mayaqua/Memory.h
Fix problem of "Wrong endianness in buffers created from node info #1555" https://github.com/SoftEtherVPN/SoftEtherVPN/issues/1555
> Fix wrong endianness in InRpcNodeInfo() and OutRpcNodeInfo()

- .ci/azure-pipelines/windows.yml
Azure CI has upgraded to Visual Studio 2022. Our template needs upgrade as well.
> Upgrade CI template for Visual Studio 2022

- src/Cedar/UdpAccel.c
On big endian system, while store 32 bits and 16 bits number in memory of  UINT64 variable ```tmp```, first 4 bytes of it always be zero make ```cookie``` and ```size``` always be zero, lead to udpaccel unusable.
> Fix udp acceleration unusable on big endian system

- .ci/azure-pipelines/windows.yml
For x86 builds, the environment `vcvarsamd64_x86` is cross compling x86 on x64 host.
But the clang compiler is x86.
By not specifying the path, the correct clang is now auto selected.
> Fix Azure environment inconsistency

- .ci/azure-pipelines/windows-steps.yml
- CMakeLists.txt
- CMakeSettings.json
- src/BUILD_WINDOWS.md
- vcpkg.json
- Create vcpkg manifest to facilitate library installation and version management
- Temporarily pin to openssl 1.1.1n (see comments below)
- Remove global library installation from Azure CI
- Add `CMakeSettings.json` to facilitate configuration in Visual Studio
- Update Windows build instructions
- Improved Azure pipeline cache key to avoid reusing outdated cache (comments below)
> Add vcpkg manifest, VS presets and update build instruction for Windows

- src/Cedar/Hub.c
- src/Cedar/Hub.h
- src/Cedar/Server.c
- src/bin/hamcore/strtable_cn.stb
- src/bin/hamcore/strtable_en.stb
- src/bin/hamcore/strtable_ja.stb
- src/bin/hamcore/strtable_ko.stb
- src/bin/hamcore/strtable_pt_br.stb
- src/bin/hamcore/strtable_ru.stb
Background
- PrivacyFilter mode is a function for administrators to restrict communication between users for security reasons.
- This option is useful for implementing the VPN user isolation.
- However, there are cases where it is necessary to allow exceptionally for communication between the same users.
(For security reasons, it is necessary to block traffic between different users, but it is often necessary to allow traffic between sessions of the same user.)
- Added [AllowSameUserInPrivacyFilterMode] option to [Virtual Hub Extended Option]
- When PrivacyFilter Mode is set and AllowSameUserInPrivacyFilterMode is Enabled, traffic between the same users is not exceptionally blocked.
> Implement additional option for PrivacyFilter Mode settings

- src/Cedar/Proto_OpenVPN.c
- I am trying to add routing to the VPN client through the DHCP classless static routing option.
- Static routing was sent as 121 code to DHCP option(destination:172.29.64.0, cidr:24, router:192.168.123.1) using external DHCP server. 
- Connected to VPN server with openvpn client.
- but,  "route 172.29.64.0 255.255.255.0 vpn_gateway" is sent in the PUSH_REPLY message. And "vpn_gateway unldefined" appears in the openvpn client log as follows.
```
2022-05-09 11:25:05 PUSH: Received control message: 'PUSH_REPLY,ping 3,ping-restart 30,topology subnet,ifconfig 192.168.123.136 255.255.255.0,dhcp-option DNS 8.8.8.8,route 172.29.64.0 255.255.255.0 vpn_gateway,block-outside-dns'
2022-05-09 11:25:05 OPTIONS IMPORT: timers and/or timeouts modified
2022-05-09 11:25:05 OPTIONS IMPORT: --ifconfig/up …
```
> Fix static route pushing to OpenVPN clients

- systemd/softether-vpnserver.service
Max pid is usually 32768 on 32-bit systems and 4194304 on 64-bit. 16777216 is way too large.
- Use `infinity` instead of a fixed number for `TasksMax`
Close #903
> Fix invalid systemd TasksMax

- src/Mayaqua/Network.c
Without `WINAPI`, the route changing callback just crashes on 32-bit Windows. 
I can't explain why it doesn't crash on x64. Sorry for that. 
I also changed `false` to `FALSE` to conform to the win32 convention.
> Fix route tracking on x86 Windows

- src/Cedar/CM.c
- src/bin/hamcore/strtable_cn.stb
- src/bin/hamcore/strtable_en.stb
- src/bin/hamcore/strtable_ja.stb
- src/bin/hamcore/strtable_ko.stb
- src/bin/hamcore/strtable_pt_br.stb
- src/bin/hamcore/strtable_ru.stb
- src/bin/hamcore/strtable_tw.stb
- Show names of connecting and connected accounts over tray icon
- Tips have been shortened to be easier to read
Feel free to suggest better wording.
Effects
Fix #1037
> Show connection names in tray tips

- src/Cedar/CM.c
On Win 11, when CM is in focus, some taskbar functions are not working properly. 
For example, right clicks on icons do not work. Some programs will open in background (below CM).
In CM we have a timer event that repeatedly puts notification service into foreground. This prevents other programs to get focus.
```c
case WM_TIMER:
switch (wParam)
{
case 1:
CmSetForegroundProcessToCnService();
break;
```
The timer event can be safely removed. The notification service is used to show connection status and only needs to be brought up when a connection is started or restarted, which is already done in `CmConnect()`.
Tested on Windows Vista and 11. More tests are welcome.
Related: #1591
> Remove CM timer event to fix taskbar behavior on Win 11

- src/BUILD_WINDOWS.md
- vcpkg.json
- Remove vcpkg baseline and unpin from OpenSSL 1.1.1 (the bug mentioned in #1578 was fixed in build 3.0.3#2)
- Update build instructions
> Remove vcpkg baseline and update docs

- src/Cedar/Hub.c
Currently we don't adjust TCP MSS for UDP acceleration sessions unless the acceleration is active (in use).
This is troublesome because UDP acceleration can turn active in the middle of a session. If an encapsulated TCP connection was started when UDP acceleration is not in use (but enabled), its MSS was not adjusted but once acceleration turns active the unadjusted TCP packets will be sent over UDP, resulting in fragmentation or packet loss.
This PR adjusts MSS for sessions that have UDP acceleration enabled, no matter in use or not.
This screenshot shows the situation when UDP acceleration turns active. You can see that data starts to be sent via UDP but is fragmented due to the size.
> Adjust TCP MSS if UDP acceleration is enabled (even if inactive)

- src/Cedar/Proto_OpenVPN.c
- src/Cedar/Proto_OpenVPN.h
OpenVPN always allowed 8 ACKs in P_ACK_V1 packets but only used
up to 4 in other control packets. Since Softether drops all packets with
more than 4 ACKs it also drops legimate P_ACK_V1.
See also this issue: https://github.com/schwabe/ics-openvpn/issues/1486
> Proto_OpenVPN: Set max allowed ACKs to 8 for P_ACK_V1

- src/Cedar/Session.c
Protocol details may contain old information when reconnecting and need to be flushed.
> Zero out protocol strings when reconnecting

- src/Mayaqua/Network.c
- src/Mayaqua/Network.h
This issue was discovered by hiura on vpnusers.com forum. 
Original post: https://www.vpnusers.com/viewtopic.php?f=15&p=96843
When we implemented routing management for IPv6 (#1443), we replaced `GetIpForwardTable` with `GetIpForwardEntry2`. However it turned out that `GetIpForwardEntry2` might include inactive routes, such as those belong to disconnected interfaces.
The solution is to filter the returned routes by querying the status of the IP interface. To maintain comparability, inactive routes are simply dropped in `Win32GetRouteTable2`. This behavior can be changed in the future.
> Exclude inactive routes in Windows routing management

- src/Cedar/CM.c
Fixes #1702.
Thanks, @domosekai!
> Cedar/CM.c: Fix wrong shortcut key assignment in the menu

- .cirrus.yml
As the stable version uses OpenSSL 3.0.x, it is nice to perform test with OpenSSL 3.0.x as well.
Also, update FreeBSD to 13.1.
> FreeBSD CI: Add test with OpenSSL 3.0.x

- src/Mayaqua/CMakeLists.txt
- Add `ws2_32.lib` and `crypt32.lib` to `CMakeLists.txt` to fix linking issues
- 
-
> Mayaqua/CMakeLists: Fix win32 build without vcpkg

- src/Cedar/Virtual.c
4272                FreeBlock(block);
    CID 375153 (#1 of 1): Uninitialized scalar variable (UNINIT)44. uninit_use: Using uninitialized value send_size. 4273                if (send_size == 0)
> src/Cedar/Virtual.c: mute Coverity warning

- src/Mayaqua/Unix.c
1875        if (mutex == NULL)
1876        {
    CID 367204 (#1 of 1): Resource leak (RESOURCE_LEAK)4. leaked_storage: Variable lock going out of scope leaks the storage it points to. 1877                return NULL;
1878        }
> src/Mayaqua/Unix.c: improve memory allocation handling according to Coverity

- src/BUILD_UNIX.md
On Ubuntu Server 22.04 LTS (and newer?), the ./configure command fails because the 'pkgconf' package is not installed by default. Suggest that the 'pkgconf' package be installed in this command line.
> add requirements package on Debian/Ubuntu

- src/Cedar/IPC.c
- src/Cedar/IPC.h
- src/Cedar/Proto_PPP.c
IPv6CP configuration in the PPP stack has issues on both sides, as detailed below.
- Client side
Currently we check the EUI proposed by the client against hub IP table and accept it if no conflict. 
If there is a conflict or the client does not propose any address, we assign one based on the IPC's MAC address.
The problem is, the IPC's MAC address is not random and can be reused from time to time.
This would lead to distinct VPN sessions using the same EUI (although not at the same time).
I propose to use a random address in case of a conflict.
- Server side
Currently we try to match the server EUI to the address of the IPv6 router by sending router solicitations.
The process can be slow if no IPv6 router is available, since we have to wait until timeout.
It's also unnecessary because the …
> Cedar/IPC: Improve IPv6CP configuration

- src/Cedar/IPC.c
- src/Cedar/IPC.h
After #1755, IPv6 router lookup is blocking. This PR changes it to non-blocking.
The lookup should not take place as long as the client is well configured because under IPv6 it is the L3 client's responsibility to send RS.
In case that the client may be misconfigured, we do the lookup at best effort without blocking.
Fix #1755
> Cedar/IPC: Change IPv6 router lookup to non-blocking

- src/Mayaqua/Network.c
`recvfrom` returns 0 for empty packets, and -1 for errors.
Treating 0 as error would cause a random error to be fetched from the error stack and unexpected behavior in UDP listeners.
> Mayaqua/Network: Fix empty packet being treated as error

- developer_tools/vpnserver-jsonrpc-clients/README.md
- Changed the jsonrpc client readme to correct the function for hashing passwords.
Changed from: SHA0( UpperCase(username_ascii_string) + password_ascii_string)
To: SHA0( password_ascii_string + UpperCase(username_ascii_string))
> Fix Incorrect password hash on documentation

- src/Mayaqua/Unix.c
This is just a cosmetic problem in the result of "Caps" command which gets the list of server functions/capability.  There's no behavioural changes in SoftEtherVPN whether running on VM so far.
> Mayaqua/Unix: Make VM detection work on FreeBSD

- README.md
Hi, I just remembered there's one more difference between Stable Edition and Developer Edition.
-----
Stable Edition requires intel_aes_lib to enable AES-NI [1]. Developer Edition depends on OpeSSL to use AES-NI. It is enabled by default as long as processor supports it.
[1] https://github.com/SoftEtherVPN/SoftEtherVPN_Stable/blob/bf23fe0/src/Mayaqua/Encrypt.c#L145-L147
> README: SEvsDE: document AES-NI hardware acceleration support

- src/Cedar/Cedar.c
This is also a cosmetic fix.
----
Before change, contiguous whitespaces appeared in version string. This room is for beta string (such as Alpha, Beta) and beta number but it looks a bit odd if the build is not alpha/beta/RC.
```
> Version 5.02 Build 5180 Alpha 3 (Japanese)
> Version 5.02 Build 5180 Beta 3 (Japanese)
> Version 5.02 Build 5180 Release Candidate 3 (Japanese)
> Version 5.02 Build 5180   (Japanese)
>                        ^^^
```
Now version string looks neat like this:
```
> Version 5.02 Build 5180 (Japanese)
> Version 5.02 Build 5180 Release Candidate 3 (Japanese)
```
------
The version string appears in the output of `vpncmd` and "About this VPN server" in Server Manager.
> Cedar: Trim contiguous whitespaces in version string

- src/Mayaqua/Memory.c
Base64 operations were refactored in #1404. However a '\0' is not added to the binary output and may corrupt memory in HTTP basic auth.
> Mayaqua/Memory: Fix memory corruption in base64

- .ci/azure-pipelines/windows.yml
- .gitignore
- CMakeLists.txt
- CMakeSettings.json
let us link MSVC runtime statically. this should eliminate the need of installing VC Redist.
thank @pizzaprogram for details
> Windows: link MSVC runtime static

- src/Cedar/Proto_OpenVPN.c
specially crafted network packet lead to buffer overrun and process crash. working exploit was provided by Cisco Talos team.
An integer underflow vulnerability exists in the vpnserver OvsProcessData functionality of SoftEther VPN 5.01.9674 and 5.02. A specially-crafted network packet can lead to denial of service. An attacker can send a malicious packet to trigger this vulnerability.
The versions below were either tested or verified to be vulnerable by Talos or confirmed to be vulnerable by the vendor.
SoftEther VPN 5.01.9674
SoftEther VPN 5.02
While 5.01.9674 is a development version, it is distributed at the time of writing by Ubuntu and other Debian-based distributions.
> src/Cedar/Proto_OpenVPN.c: fix denial of service found by Cisco Talos

- src/Mayaqua/Str.c
TALOS-2023-1741
CVE-2023-23581
SoftEther VPN vpnserver EnSafeHttpHeaderValueStr denial of service vulnerability
A denial of service vulnerability exists in the vpnserver EnSafeHttpHeaderValueStr functionality of SoftEther VPN 5.01.9674 and 5.02. A specially-crafted network packet can lead to denial of service.
> src/Mayaqua/Str.c: fix denial of service reported by Cisco Talos

- src/Mayaqua/Unix.c
SoftEtherVPN/src/Mayaqua/Unix.c:51:25: warning: missing terminating ' character
51 | #include <sys/statvfs.h>'
> src/Mayaqua/Unix.c: fix guarding

- src/Cedar/Server.c
```
================================================================= ==1505093==ERROR: AddressSanitizer: heap-use-after-free on address 0x607000366b88 at pc 0x7f72afadc34a bp 0x7f72990fa390 sp 0x7f72990fa388 READ of size 4 at 0x607000366b88 thread T22
#0 0x7f72afadc349 in GetCaps /home/ilia/SoftEtherVPN/src/Cedar/Server.c:1861
#1 0x7f72afadc382 in GetCapsInt /home/ilia/SoftEtherVPN/src/Cedar/Server.c:1802
#2 0x7f72afaf72a5 in GetServerCapsInt /home/ilia/SoftEtherVPN/src/Cedar/Server.c:1098
#3 0x7f72afaf7318 in GetServerCapsBool /home/ilia/SoftEtherVPN/src/Cedar/Server.c:1104
#4 0x7f72afaf771e in SiWriteHubCfg /home/ilia/SoftEtherVPN/src/Cedar/Server.c:4887
#5 0x7f72afaf771e in SiWriteHubCfg /home/ilia/SoftEtherVPN/src/Cedar/Server.c:4824
#6 0x7f72afaf7c0b in SiWriteHubs …
```
> src/Cedar/Server.c: fix race condition

- src/Cedar/Cedar.h
- src/Cedar/Client.c
- src/Cedar/SM.c
- src/Cedar/VLanUnix.c
- src/Cedar/VLanUnix.h
As a result of this PR, vpnclient functionality on FreeBSD has become more practical.
- Don't hardcode prefix for UNIX virtual network interface
- Make NicDelete work on FreeBSD
-  Virtual network interfaces are properly cleaned up when shutting down vpnclient
- Make NIC state change (up/down) work on FreeBSD
-  Virtual network interface state is set to up when attempt to VPN server
Fixes: #1858
> FreeBSD: Improve client's virtual network interface handling

- src/Cedar/VLanUnix.c
In addition to #1859, added interface description to the tap interface.
```
$ ifconfig vpn_client
vpn_client: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
description: SoftEther Virtual Network Adapter <-- THIS IS IT!
options=80000<LINKSTATE>
ether 5e:51:5e:48:ea:ef
hwaddr 58:9c:fc:10:34:2a
groups: tap
media: Ethernet autoselect
status: active
nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
Opened by PID 35981
```
> Cedar/VLanUnix: add description to FreeBSD tap device

- src/Cedar/BridgeUnix.c
- src/Cedar/Cedar.h
- src/Cedar/SM.c
- src/Cedar/VLanUnix.c
- src/Cedar/VLanUnix.h
This PR applies the same fix as well as #1859 for the bridge destination tap interface.
1. No tap interfaces before starting vpnbridge.
```
root@freebsd:~/SoftEtherVPN/build # ifconfig -a -g tap
root@freebsd:~/SoftEtherVPN/build #
```
2. Bridge tap device is created after starting vpnbridge.
```
root@freebsd:~/SoftEtherVPN/build # ./vpnbridge start
root@freebsd:~/SoftEtherVPN/build # ./vpncmd /server localhost /cmd:bridgelist
BridgeList command - Get List of Local Bridge Connection
Number|Virtual Hub Name|Network Adapter or Tap Device Name|Status
------+----------------+----------------------------------+---------
1     |BRIDGE          |bridge                            |Operating                        
The command completed successfully.         
root@freebsd:~/SoftEtherVPN/build # …
```
> FreeBSD: Make sure to destroy tap device for bridge

- src/Mayaqua/Unix.c
Fails to build after:
https://cgit.freebsd.org/src/commit/?id=a681cba16d8967651a2146385ce44a2bfeb1c4c3
As the commit title is "Bump __FreeBSD_version for llvm 16.0.6 merge", I suppose LLVM 16 is stricter than LLVM 15. It was building successfully at least the previous week.
Build log: https://pkg-status.freebsd.org/beefy18/data/main-amd64-default/p4785b313b958_se8efee297c/logs/softether5-5.02.5180.335,2.log
```
[ 32%] Building C object src/Mayaqua/CMakeFiles/mayaqua.dir/Unix.c.o
cd /wrkdirs/usr/ports/security/softether5/work/.build/src/Mayaqua && /usr/bin/cc -DBRIDGE_BPF -DCPU_64 -DHAVE_SSL_CTX_SET_NUM_TICKETS -DNDEBUG -DOS_UNIX -DREENTRANT -DSE_DBDIR=\"/var/db/softether\" -DSE_LOGDIR=\"/var/log/softether\" -DSE_PIDDIR=\"/var/run/softether\" …
```
> Fix build on __FreeBSD_version >= 140091 (LLVM 16)

- src/Cedar/BridgeUnix.c
- src/Cedar/Client.c
Occurred at:	 #670
Closes:		#1864
Tested build on FreeBSD with NO_VLAN by modifying CMakeLists.txt like this:
```diff
diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
index c49a3c78..1dad3691 100644
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -93,6 +93,7 @@ if(UNIX)
if(${CMAKE_SYSTEM_NAME} STREQUAL "FreeBSD")
add_definitions(-DUNIX_BSD -DBRIDGE_BPF)
+    add_definitions(-DNO_VLAN)
include_directories(SYSTEM /usr/local/include)
link_directories(SYSTEM /usr/local/lib)
endif()
```
> Fix build when NO_VLAN

- src/Cedar/VLanUnix.c
- src/Cedar/VLanUnix.h
This is the final one of the series of pull requests I have been working on improving SoftEther bridge/client functionality on FreeBSD.
#1859, #1860, #1863 and this one.
-----
Interface grouping is available on FreeBSD and OpenBSD. This will allow you to enumerate only SoftEther virtual interfaces or exclude SoftEther virtual interfaces, and be helpful when making custom scripts to start DHCP client when virtual interface become up (=VPN connection established) for example.
Usage examples as follows.
List all interfaces' names available on the system:
```
$ ifconfig -l
vtnet0 lo0 vpn_client0 vpn_client1 vpn_client2
```
Display a list of SoftEther virtual interfaces:
```
$ ifconfig -g softether
vpn_client0
vpn_client1
vpn_client2
```
Display details about SoftEther virtual interfaces that …
> Cedar/VLanUnix: assign virtual interface to softether group

- src/Mayaqua/Network.h
- src/Mayaqua/TunTap.h
1. `pthread.h` should be included also on macOS, otherwise `pthread_t` is undefined.
2. `sys/types.h` is needed with `_DARWIN_C_SOURCE` in order to `u_char` and `u_short` be recognized.
> Fix macOS build: add missing headers

- src/Cedar/Protocol.c
- Fix the bug below 
Change sess->ClientOption->BindLocalIP  to &sess->ClientOption->BindLocalIP in ClientConnectGetSocket()
- Others
-
> Fix access violation: correct typing mistake in calling Debug(). 

- .ci/azure-pipelines/windows-steps.yml
- Published binaries include only either X64 or X86. Not both. 
- Separate the directories for both X64 and X86 to publish binary files.
Binaries_x64
Binaries_x86
Installers
> Fix azure pipelines: Publish separate artifacts for both x64 and x86.

- src/Cedar/IPC.c
- Cast the void pointer to UCHAR *. 
- The reason is
- MSVC compiler generates error below.
error C2036: 'void *' : unknown size
- I can't perform pointer arithmetic on a void * because void doesn't have a defined size.
Cast the pointer to UCHAR * and it will work as expected.
> IPC.c: Cast the pointer to a defined size due to the error in compiling.

- src/BUILD_UNIX.md
Correct location for build output dir.
- In this build instruction, artifacts are outputs to **build/** directory. But, _'using without installation'_ heads to the **bin/** directory, so correct to **build/**.
> Update BUILD_UNIX.md for fix location

- src/Cedar/Session.c
- "Session Timeouted." occurs.
- How to reproduce.
①run VPN Client.
②Set the number of tcp connections to 32 on "advanced settings" screen.
③Set the source port number to 55551 for example. Not zero value is to be required.
④click to connect.
⑤confirm that session of around or more than  29 TCP connections is killed by itself due to the unsuitable time.
- Change the time for checking whether or not all the TCP cnnections are alive.
from "after a certain time from the first TCP connection" to "after a certain time from the last TCP connection".
> Fix "Session Timeouted.":  Change the time for checking wether all the TCP connectins are alive or not.

- src/Mayaqua/Microsoft.c
- src/Mayaqua/Microsoft.h
- src/Mayaqua/Network.c
- DHCP client can not get default GW address and DNS address.
- Preparation before reproducing:
①Plug the "USB ETHERNET ADAPTER 2" into PC2 once. The MAC address of it will be saved in WIN11 of PC2.
②Set up local bridge in PC1. Also in PC2.
③Set up cascade connection in PC1.
④Set RemoveDefGwOnDhcpForLocalhost to false in "vpn_server.config" in PC1.
⑤Set RemoveDefGwOnDhcpForLocalhost to true  in "vpn_server.config" in PC2.
- How to reproduce:
①Run VPN SERVER in PC1.
②Run VPN SERVER in PC2.
③Plug the "USB ETHERNET ADAPTER 2" into PC1 to access LAN.  This adapter is used in PC2 before.
④Confirm that the "USB ETHERNET ADAPTER 2" can not get default GW address and DNS address.
- Change to exclude unplugged device from MAC address list.
DHCP client will …
> Fix "RemoveDefGwOnDhcpForLocalhost" function: Change to exclude unplugged device from MAC address list.

- src/Cedar/Protocol.c
This patch addresses such a scenario when OpenVPN clients utilize the certificate-only authorization scheme. It works out-of-the box in case `cn_username` contains a 'plain' username that is identical to corresponding user name of default Hub user database. However, if `cn_username` is in `user@domain.tld` format, the whole `cn_username` string is compared to Hub user database entries and does not match as Hub usernames cannot contain `@` sign.
- If `cn_username`  contains @ sign, it is being split into user name and domain name which are being passed along as `username` and `hubname`, respectively.
- If `cn_username` does not contain @ sign, `username` and `hubname` are set as usual.
This patch has been tested on an experimental installation and …
> OpenVPN certificate authorization with cn_username in 'email' format

- src/Cedar/BridgeUnix.c
On FreeBSD the stock code will attempt to expand the interface MTU any time a packet is to be sent that exceeds the current MTU.  This results in a down/up on the interface that is wildly disruptive to existing services on that adapter and, eventually, is likely to run into MTU limits and start logging failures, even with jumbo-frame capable adapters.  Thus if compiling on a FreeBSD machine disable this capability.  Tested against 12.3-STABLE and 13.1-STABLE on v4.38-9760 from the FreeBSD ports tree but likely applies here as well; see bug report https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=267178
- 
- 
-
> BridgeUnix.c: Disable MTU changes on FreeBSD

- src/Cedar/IPC.c
Apparently we don't always get the RouterLinkLayerAddress, so it is null, and we crash. Fixing that. Made sure that this case is handled appropriately when we actually resolve the prefixes later
Should fix #1972
> Fix memory access error when IPv6 prefix reading, should resolve #1972

- CMakeLists.txt
A library problem occurred when building and installing on a RHEL-based distribution.
The cause is that even though the library is installed in the lib64 directory, the executable file looks for the lib directory.
To solve this problem, I changed part of CMakeLists.txt.
This problem also occurs on Gentoo Linux.
My environment
```
$ cat /etc/redhat-release 
MIRACLE LINUX release 9.2 (Feige)
$ uname -a
Linux localhost.localdomain 5.14.0-284.11.1.el9_2.x86_64 #1 SMP PREEMPT_DYNAMIC Fri May 26 02:39:48 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```
p.s.
With the help of @nvsofts , I have solved this problem.
> Change var of CMAKE_INSTALL_RPATH

- .github/workflows/macos.yml
more details: https://github.blog/changelog/2024-05-20-actions-upcoming-changes-to-github-hosted-macos-runners/
> CI: drop macos-11

- src/Cedar/Virtual.c
- src/Mayaqua/Network.c
- DHCP_NAK does not work correctlly
- Changes make it work correctlly
- Description of changes: 
①If IP address in user's note is changed, then reply to DHCP REQUEST with DHCP NAK.
This makes DHCP sequence begin with DHCP DISCOVER.
②If there is any entry with the same MAC address, then remove it.
Unused lease time record is deleted from IP lease table.
③Reassigning static IP address is partially modified.
④Thease changes enable to switch between static and dynamic IP address assignment.
Users do not need to restart the VPN server.
- Example below:
Already set to IPv4:192.168.30.222 in user's note.
First, set to IPv4:192.168.30.234 in user's note. Indicated with yellow line.
Second, delete IPv4:192.168.30.234 from user's note. Indicated with yellow …
> Fix Virtual DHCP Server: Correct IP reassignment

- .cirrus.yml
since FreeBSD 13.2 image is no longer available on the CI platform.
> CI: Update to FreeBSD 14.0-RELEASE

- .github/workflows/fedora-rawhide.yml
- src/Mayaqua/Encrypt.c
Fedora Rawhide's ```openssl-devel``` package does not support engines (it is built with the no-engine flag). However, it does not define OPENSSL_NO_ENGINE. This seems to be a bug.
This pull requests adds the ability to build with any OpenSSL that does not have engine support that *correctly* defines OPENSSL_NO_ENGINE. It also replaces ```openssl-devel``` with ```openssl-devel-engine``` for the Fedora test, to workaround the issue.
> Fix openssl engine support on Fedora Rawhide

- README.md
Based on issue #1993, the build has been moved from Azure to Github.
- URL for Nightly builds  for Windows
> URL for Nightly builds  for windows is updated

- CMakeLists.txt
Update required cmake version to the actual state:
* 3.12 is required for add_compile_definitions introduced with edcdc923ad2b4feaf25080412a57f560093f725e on Jan 31st, 2023.
* 3.15 is required for CMP0091 policy introduced with 96ab9691521b7352b4c13b347dfe9ec9cd2850d9 on March 11th, 2023.
Only two distros have cmake of lower version according to https://pkgs.org/download/cmake:
* RHEL 8: 3.11.4
* Debian 10: 3.13.4. Debian 10 is supported until June 30th, 2024.
Since there are no issues about cmake version, I think there is no need to keep it low.
Closes #2040
> Update minimal cmake version to 3.15

- src/Mayaqua/Microsoft.c
- src/Mayaqua/Microsoft.h
- src/vpncmd/vpncmd.c
Fixes https://github.com/SoftEtherVPN/SoftEtherVPN/issues/2031
Running vpnclient.exe fails because ```ms->IsNt``` is never set to true. This seems to be old code from the stable branch that was never changed to ```IsNt()```.
This pull request changes changes ```ms->IsNt``` to ```IsNt()```, and removes ```IsNt``` from the ```MS``` struct, because it is no longer necessary.
> Fix "Not on NT" error message and add uihelp to vpncmd

- systemd/softether-vpnbridge.service
- systemd/softether-vpnclient.service
- systemd/softether-vpnserver.service
- Change to start the services directly. Systemd services do not require those command line wrappers.
- Remove misused `EnvironmentFile=`. It should be pointed to a text file, not a directory.
- Remove `KillMode=process` which is not recommended by _systemd.kill(5)_. The default `control-group` would be fine.
> Correct and simplify systemd service files

- .github/workflows/linux.yml
- Simple Workflow change to download deb packages created within the Linux workflow
> Adding artifact publishing for Linux

- docker-compose.yaml
Fixes SoftEtherVPN/SoftetherVPN-docker#15 by configuring static hostname
> set static hostname in docker-compose so ddns feature works cross restarts

- SoftEtherVPN-iOS/SoftEtherVPN-iOS/Protocol/SecureConnection.swift
- SoftEtherVPN-iOS/SoftEtherVPN-iOS/Protocol/SoftEtherClientSignature.swift
- SoftEtherVPN-iOS/SoftEtherVPN-iOS/Protocol/SoftEtherCrypto.swift
- SoftEtherVPN-iOS/SoftEtherVPN-iOS/Protocol/SoftEtherPacket.swift
- SoftEtherVPN-iOS/SoftEtherVPN-iOS/Protocol/SoftEtherProtocol.swift
- SoftEtherVPN-iOS/SoftEtherVPN-iOS/SoftEtherVPNClient.swift
The implementation includes the following key components:
SoftEtherProtocol.swift: The main protocol handler that manages the connection to the SoftEther VPN server. It handles establishing the TLS connection and sending the proper client signature.
SecureConnection.swift: Handles the low-level TLS communication using Apple's Network framework.
SoftEtherPacket.swift: Implements the binary packet structure that SoftEther uses for communication.
SoftEtherCrypto.swift: Provides cryptographic operations needed by the protocol, including SHA-1, MD5, and RC4 encryption.
SoftEtherClientSignature.swift: Specifically focuses on generating the correct client signature format that the server expects after TLS handshake.
SoftEtherVPNClient.swift: A higher-level …
> Add iOS client implementation with SoftEther protocol handshake support
