.github/PULL_REQUEST_TEMPLATE.md

this will speed up PR adoption. developers will answer with either "1" or "2" right after PR is created

added github PR template

---

src/Mayaqua/Secure.h

Tested on RuToken-S key.
https://www.rutoken.ru/products/all/rutoken-s/

Added support for RuToken USB key PKCS#11

---

src/Cedar/Logging.c

Fix log msg for IKE with agressive exchange mode

---

src/Cedar/Admin.c
src/Cedar/Protocol.c
src/Cedar/WebUI.c
src/Mayaqua/Cfg.c
src/Mayaqua/Encrypt.c
src/Mayaqua/Internat.c
src/Mayaqua/Network.c

issues were identified by running (cppcheck)
```
script
cppcheck --force --enable=all
Ctrl-D
grep '(error' typescript
grep '(warning' typescript
```
and (clang static analyzer)
```
./configure
scan-build make
```
identified issues are mostly related to "derefence var before checking againts NULL"
cppcheck findings are described in their commit messages

cppcheck findings

---

src/Mayaqua/Encrypt.c

Add the Alternative subject name field on the new X.509 certificate creation.

Add the Alternative subject name field on the new X.509 certificate creation.

---

README.md
centos/SPECS/softethervpn.spec
debian/changelog
src/BUILD_UNIX.md

- README.me file is updated to use the latest Ubuntu package names.
- src/BUILD_UNIX.md updated with Ubuntu commands.
- Option 1

Updated build instructions and package versions

---

src/Mayaqua/Network.c

This patch fixes an OpenSSL 1.1.0 compilation problem introduced in #327.

Fix compilation with OpenSSL 1.1.0 (broken in #327)

---

.github/ISSUE_TEMPLATE

Hi, there!
Thank you for using SoftEther.
Before you submit an issue, please read the following:
Is this a question?
- If the answer is "yes", then please ask your question on [www.vpnusers.com](http://www.vpnusers.com).
The issue section on GitHub is reserved for bugs and feature requests.
- If the answer is "no", please read the following:
We provide a template which is specifically made for bug reports, in order to be sure that the report includes enough details to be helpful.
Please use or adapt it as needed.
---
**SoftEther version:**
**Component:** [Server, Client, Bridge, etc.]
**Operating system:** [Windows, Linux, BSD, macOS, etc.]
**Architecture:** [64 bit, 32 bit]
[In case it's a computer with known specs, such as the Raspberry Pi, you can specify it omitting the details.] …

GitHub: Improve issue template

---

debian/README.TXT

debian: correct date in README.TXT

---

.appveyor.yml

- store build artifacts in app veyor
- 
- 
- one

appveyor: store build artifacts

---

.github/PULL_REQUEST_TEMPLATE.md

Add a sentence: "preliminary declaration for future change to non-GPL licenses" on pull requests.

Add a sentence: "preliminary declaration for future change to non-GPL licenses" on pull requests.

---

.ci/before_install.sh
.ci/build-openssl.sh
.ci/script.sh
.travis.yml
src/makefiles/macos_32bit.mak
src/makefiles/macos_64bit.mak

Commit d478cd97bf6fb7616d0b5eda92fef54c3b4191b4 fixes #216.
---

Travis CI: add MacOS target and create scripts files

---

src/Cedar/Admin.c
src/bin/hamcore/openvpn_sample.ovpn

OpenVPN: don't generate dummy certificates

---

README.md

- link to Launchpad PPA is added to REAME
- 
- 
- one

added launchpad PPA to README

---

src/Cedar/Server.c

Server.c: remove dead for() loop used to add test users to the default hub

---

src/BUILD_UNIX.md

- minor build documentation improvement
- 
- 
- 1

BUILD_UNIX.md: improve documentation as discussed in #558

---

src/BuildUtil/CopyBuildUtil.cmd

CopyBuildUtil.cmd: fix copy failure when the path contains whitespaces

---

.travis.yml

Travis CI: upgrade everything on MacOS

---

.travis.yml

https://github.com/SoftEtherVPN/SoftEtherVPN/pull/598#issuecomment-409547990
---

Travis CI: cache Homebrew downloads

---

src/Cedar/Interop_OpenVPN.c
src/Mayaqua/Kernel.c
src/Mayaqua/Kernel.h
src/Mayaqua/Network.c
src/Mayaqua/Tracking.c
src/Mayaqua/Unix.c

- improving coverity reports, no real impact or changes
- 
- 
- one

resolve several trivial issues found by Coverity

---

.travis.yml
debian/rules
debian/softether-vpnbridge.install
debian/softether-vpnclient.install
debian/softether-vpncmd.install
debian/softether-vpnserver.install

- fix launchpad builds
- 
- 
- one

another attempt to fix launchpad builds

---

src/Cedar/BridgeUnix.c
src/Mayaqua/FileIO.c

- initialize variables
- 
- 
- one

initialize variables (it makes coverity a bit happier)

---

README.md

https://gitlab.com/SoftEther/SoftEtherVPN
---

README.md: add GitLab repository

---

src/BUILD_UNIX.md

BUILD_UNIX.md: add commands to checkout the submodule(s)

---

src/Mayaqua/Encrypt.c

```c
/builds/SoftEther/SoftEtherVPN/src/Mayaqua/Encrypt.c: In function 'RsaCheck':
/builds/SoftEther/SoftEtherVPN/src/Mayaqua/Encrypt.c:2307:3: warning: 'RSA_generate_key' is deprecated [-Wdeprecated-declarations]
rsa = RSA_generate_key(bit, RSA_F4, NULL, NULL);
^~~
In file included from /usr/include/openssl/rsa.h:13:0,
from /usr/include/openssl/x509.h:31,
from /usr/include/openssl/ssl.h:50,
from /builds/SoftEther/SoftEtherVPN/src/Mayaqua/Encrypt.c:127:
/usr/include/openssl/rsa.h:193:1: note: declared here
DEPRECATEDIN_0_9_8(RSA *RSA_generate_key(int bits, unsigned long e, void
^
```
```c
/builds/SoftEther/SoftEtherVPN/src/Mayaqua/Encrypt.c: In function 'RsaGen':
/builds/SoftEther/SoftEtherVPN/src/Mayaqua/Encrypt.c:2377:3: warning: 'RSA_generate_key' is deprecated …
```

Encrypt.c: don't use deprecated OpenSSL functions

---

src/Cedar/DDNS.c
src/Mayaqua/Cfg.c
src/Mayaqua/FileIO.c
src/Mayaqua/Network.c

- several issues found by coverity
- 
- 
- one

fix several issues found by coverity

---

src/BUILD_UNIX.md

Change the order of commands SE manual installation docs

---

src/Cedar/Client.c
src/Cedar/Hub.c
src/Cedar/IPsec_IKE.c
src/Cedar/IPsec_PPP.c
src/Cedar/Session.c
src/Mayaqua/Cfg.c

- resolve several issues found by coverity
- 
- 
- one

resolve several issues found by coverity

---

.ci/coverity.sh
.travis.yml

- add coverity scan to master branch
- 
- 
- one

add coverity scan to travis-ci matrix

---

.gitignore
.travis.yml
CMakeLists.txt
src/vpnbridge/CMakeLists.txt
src/vpnclient/CMakeLists.txt
src/vpncmd/CMakeLists.txt
src/vpnserver/CMakeLists.txt

This is in preparation for CPack.
---

CMake: change output directory from "bin" to "build"

---

.ci/coverity.sh
.travis.yml

- change branch filter to "master"
- remove not needed "secure" variable
- 
- one

travis-ci: small coverity fixes

---

src/Cedar/EtherLog.c
src/Cedar/Nat.c
src/Cedar/Session.c
src/Mayaqua/Tick64.c

- resolve several issues identified by coverity
- 
- 
- one

resolve several issues identified by coverity

---

.gitlab-ci.yml
configure

- dpkg-dev installed
-  3.12.1 moved to variables
-  tar silenced
- unneeded variable CMAKE removed
- one

gitlab-ci: refactoring

---

src/Cedar/BridgeUnix.c
src/Cedar/BridgeUnix.h
src/Cedar/Client.c
src/Cedar/Client.h
src/Cedar/Command.c
src/Cedar/Command.h

- null pointer dereference resolved
- unused functions, variables removed
- dead code removed
- one

resolve several coverity issues

---

src/Cedar/Client.c
src/Cedar/Virtual.c
src/Mayaqua/Network.c
src/Mayaqua/Unix.c

- silence coverity issues
- 
- 
- one

silence several coverity "issues"

---

src/bin/hamcore/languages.txt

Add Russian language to translate.txt

---

src/Cedar/Session.c
src/Cedar/Session.h

src/Cedar/Session: resolve coverity "issue", remove unused functions

---

src/Cedar/BridgeUnix.c

src/Cedar/BridgeUnix.c: resolve possible null pointer dereference

---

src/Cedar/Server.c
src/Cedar/Server.h

src/Cedar/Server: resolve possible null reference exception, remove unused functions, variable, duplicate assignment and conditional

---

.travis.yml
src/CMakeLists.txt
systemd/softether-vpnbridge.service
systemd/softether-vpnclient.service
systemd/softether-vpnserver.service

CMake: install systemd configuration files

---

src/Cedar/Hub.c
src/Cedar/Hub.h

src/Cedar/Hub: resolve potential null pointer dereference, remove unused functions

---

src/Cedar/Radius.c

src/Cedar/Radius: resolve several coverity "issues"

---

src/Cedar/Client.c

src/Cedar/Client.c: remove not needed condition

---

src/Cedar/BridgeUnix.c

BridgeUnix.c: add TAP local bridge support for FreeBSD

---

.travis.yml

travis-ci: run stbcheck utility

---

.travis.yml

travis-ci: setup releases from tags

---

.gitignore

Added some output/obj folders to git ignore.

---

src/Cedar/Client.c
src/Cedar/Connection.c
src/Cedar/Hub.c
src/Cedar/Protocol.c
src/Cedar/Server.c
src/Cedar/Virtual.c
src/Cedar/WebUI.c
src/Mayaqua/Kernel.c
src/Mayaqua/Network.c
src/Mayaqua/Secure.c
src/Mayaqua/TcpIp.c
src/Mayaqua/Unix.c

- Fix bugs reported by Coverity Scan.
- 1

Fix bugs reported by Coverity Scan.

---

src/Cedar/BridgeUnix.c
src/Mayaqua/Object.c

src/Cedar/BridgeUnix.c: resolve null pointer dereference

---

src/Mayaqua/Encrypt.c

Encrypt.c: fix MdProcess()'s HMAC implementation

---

AUTHORS.TXT

AUTHORS.TXT: move development board members into a dedicated section

---

src/Mayaqua/Network.c

This pull request improves the `RecvFrom()` and `RecvFrom6()` functions by:
- Using the right data type for the struct size variable passed to `recvfrom()`.
- Improving the arguments validation mechanism.
- Printing unhandled errors.
---

Mayaqua/Network.c: improve RecvFrom() and RecvFrom6()

---

src/vpntest/vpntest.c

- vpntest improvement: add Server Manager UI and Client Manager UI test
-1

vpntest improvement: add Server Manager UI and Client Manager UI test

---

.gitlab-ci.yml
CMakeLists.txt
src/Mayaqua/CMakeLists.txt
src/Mayaqua/Encrypt.c

gitlab-ci: enable ubuntu 12.04 builds

---

src/hamcorebuilder/hamcorebuilder.c

hamcorebuilder.c: check for "_DEBUG" macro and don't enable memcheck

---

src/Mayaqua/MayaType.h

src/Mayaqua/MayaType.h: fix extra bracket

---

src/Cedar/Logging.c

src/Cedar/Logging.c: clean compiler warning

---

.appveyor.yml
.gitlab-ci.yml
CMakeLists.txt
src/CMakeLists.txt
src/vpnbridge/CMakeLists.txt
src/vpnclient/CMakeLists.txt
src/vpnserver/CMakeLists.txt
systemd/softether-vpnbridge.service
systemd/softether-vpnclient.service
systemd/softether-vpnserver.service

adjust systemd paths according to installation path

---

.appveyor.yml
CMakeLists.txt
src/CMakeLists.txt

CMake: add dynamic libraries to RPATH

---

.appveyor.yml
.gitmodules
CMakeLists.txt
configure.cmd
src/CMakeLists.txt
src/Cedar/CMakeLists.txt
src/Mayaqua/CMakeLists.txt
src/PenCore/CMakeLists.txt
src/hamcorebuilder/hamcorebuilder.c
src/vpnbridge/CMakeLists.txt
src/vpnclient/CMakeLists.txt
src/vpncmd/CMakeLists.txt
src/vpncmgr/CMakeLists.txt
src/vpnserver/CMakeLists.txt
src/vpnsmgr/CMakeLists.txt
src/vpntest/CMakeLists.txt

A Visual Studio 2017 build is added to AppVeyor, the artifacts consist in a `zip` archive containing the binaries and `hamcore.se2`.
---

CMake: add support for Windows (Visual C++ 2017 toolset)

---

.appveyor.yml
.ci/appveyor_afterbuild.sh
.gitlab-ci.yml

ci repair and refactoring

---

.appveyor.yml

AppVeyor: non interactive mode of journalctl

---

.appveyor.yml
.ci/memory-leak-test.sh

AppVeyor: run "vpntest" for ubuntu 18.04

---

README.md

README.md: add gitlab-ci badge

---

src/Cedar/Proto_OpenVPN.c

This is in preparation for GCM ciphers support.
---

Proto_OpenVPN.c: move encrypt and decrypt process into dedicated functions

---

.appveyor.yml
.ci/appveyor_afterbuild.sh

AppVeyor: enable parallel builds and push systemctl log as artifact

---

src/Cedar/Proto_IkePacket.c
src/Cedar/Proto_IkePacket.h

src/Cedar/Proto_IkePacket: remove unused functions, redundant assignment

---

src/Cedar/Protocol.c
src/Cedar/Protocol.h
src/Cedar/Session.h

src/Cedar/Protocol, src/Cedar/Session: cleanup, remove unused functions, variables

---

.ci/build-libressl.sh
.ci/build-openssl.sh
.travis.yml

travis-ci: add libressl build, make builds parallel, remove not needed brew

---

src/Cedar/Proto_OpenVPN.c

Fixes #333.
Mikrotik's OpenVPN implementation sends two consecutive `P_CONTROL_HARD_RESET_CLIENT_V2` packets, resulting in the data channel being released here: https://github.com/SoftEtherVPN/SoftEtherVPN/blob/264760aaf593d3d12fba76cee9b9bb610c742367/src/Cedar/Proto_OpenVPN.c#L527-L533
The server proceeds then to create a new data channel, but the client is left in a "partially connected" state, which is why RouterOS complains about the duplicate packets (double channel initialization).
The fix consists in checking whether the data channel is established before releasing it.
---

Cedar/Proto_OpenVPN.c: don't release data channel if it's not established, improve logic and debug messages

---

.appveyor.yml
.ci/appveyor-vpntest.ps1

AppVeyor: renew github token, renamed APPVEYOR_REPO_TAG to upper case,

---

.travis.yml

travis-ci: do not do anything on tag, source is packed automatically

---

src/Cedar/Account.c

Cedar: allow @ in username

---

src/Mayaqua/Mayaqua.c
src/Mayaqua/Mayaqua.h

src/Mayaqua/Mayaqua: remove unused functions

---

src/Cedar/Listener.c

Cedar: Bind the special listeners to the specified IP address

---

.appveyor.yml
.gitlab-ci.yml
azure-pipelines.yml
configure

setup azure pipelines

---

src/bin/hamcore/strtable_cn.stb

fixed a typo ("取消l" => "取消")
***
I choose 1.

Fixed a typo in Chinese translation

---

.ci/run-openvpn-tests.sh
.ci/start-se-openvpn.sh
azure-pipelines.yml

run openvpn tests within Azure Pipelines

---

src/Cedar/DDNS.c
src/Cedar/DDNS.h
src/Cedar/Proto_IPsec.c
src/Cedar/Proto_IPsec.h
src/Cedar/Proto_SSTP.c
src/Cedar/Proto_SSTP.h
src/Cedar/Protocol.c
src/Cedar/Protocol.h
src/Cedar/UT.c
src/Cedar/UT.h
src/Mayaqua/FileIO.c
src/Mayaqua/FileIO.h

remove unused functions

---

src/bin/hamcore/vpninstall_cn.inf

- Fixed weird translations.
- I choose 1.

Improve translations for inf file.

---

src/Mayaqua/CMakeLists.txt

disable cpu features on arm64, amrhf, s390x

---

src/Mayaqua/Encrypt.c

Fix compilation without OpenSSL ENGINE

---

src/Mayaqua/Encrypt.c
src/Mayaqua/Mayaqua.c

- Fixed memory leaks in OpenSSL deinitialization function.

Fix memory leak in OpenSSL deinitialization function

---

src/Mayaqua/Encrypt.c

Fixed the vulnerability that a malformed packet will cause the buffer overflow at the receive path. This vulnerability may occur abnormal process exit with the buffer security check mechanism built-in with SoftEther VPN binary. Although this buffer overflow can theoretically bypass the security check in theory, in the actual binary it is detected by the buffer security check inserted by the C compiler and the process is forcibly terminated. Therefore, as a result, it can be abused by a DoS attacker. Acknowledgments: The last problems is discovered and reported by Fabrizio Steiner.

Fixed the RsaVerifyEx function buffer overflow problem

---

.azure-pipelines.yml
.ci/azure-pipelines-linux.yml
.ci/azure-pipelines-win.yml

Azure Pipelines: refactoring, adding windows target

---

.ci/azure-pipelines-linux.yml
.ci/azure-pipelines-win.yml

azure pipelines improvements

---

.travis.yml

travis-ci: add linux-ppc64le to build matrix

---

systemd/softether-vpnserver.service

This PR increases the maxtasks for the systemd service of the vpnserver.
The maximum number is based on maximum connections per hub * maximum hubs. 
This PR is related to #903

Increased the task limit of the unit file

---

.travis.yml

travis-ci: update dotnet sdk version

---

src/See/Packet.c

- Added ProbeForWrite() buffer writable check routine for Irp->UserBuffer in the See driver. The See driver is a legacy driver for packet capturing with NDIS 5.x (Windows 2000 or XP). It is based on the source code of WinPcap.

Added ProbeForWrite() buffer writable check routine for Irp->UserBuffer in the NDIX 5.x See driver.

---

developer_tools/vpnserver-jsonrpc-clients/README.html
developer_tools/vpnserver-jsonrpc-clients/README.md
developer_tools/vpnserver-jsonrpc-codegen/Templates/doc.txt
src/bin/hamcore/vpnserver_api_doc.html

- Fix incorrect URLs in text files

Fix incorrect URLs in text files

---

src/Cedar/SW.c
src/Mayaqua/Microsoft.c
src/Mayaqua/Microsoft.h
src/bin/hamcore/strtable_cn.stb
src/bin/hamcore/strtable_en.stb
src/bin/hamcore/strtable_ja.stb
src/bin/hamcore/strtable_ko.stb
src/bin/hamcore/strtable_ru.stb
src/bin/hamcore/strtable_tw.stb

- Add the warning message if KB3033929 is not installed in Windows 7 / Server 2008 R2.

Add the warning message if KB3033929 is not installed in Windows 7 / Server 2008 R2.

---

FUNDING.yml

add FUNDING.yml

---

.ci/sonarcloud.sh
.travis.yml

travis-ci: add sonar-scan, update openssl, libressl

---

.ci/build-openssl.sh
src/Mayaqua/Encrypt.c
src/Mayaqua/Encrypt.h

Deprecated API fixes. Again...

Deprecated OpenSSL API fixes.

---

src/Cedar/Sam.c
src/Mayaqua/Encrypt.c
src/Mayaqua/Network.c

Fix several compile warnings on MS VC++ 2008.

Fix several compile warnings on MS VC++ 2008.

---

systemd/softether-vpnbridge.service
systemd/softether-vpnclient.service
systemd/softether-vpnserver.service

systemd: replace deprecated CAP_SYS_ADMIN with CAP_SYSLOG

---

src/Cedar/Proto_OpenVPN.c
src/Cedar/Proto_OpenVPN.h

Addressing the OpenVPN UDP reflection amplification attack: https://github.com/SoftEtherVPN/SoftEtherVPN/issues/1001

Addressing the OpenVPN UDP reflection amplification attack

---

src/Cedar/Proto_OpenVPN.c

Coverity Scan detected an out-of-bounds access issue: `OvsProcessData()` checked whether the payload size was bigger than the size of the buffer, instead of checking whether the entire packet size (payload size + 2 bytes) was, resulting in an out-of-bounds access in case the payload size is bigger than 1998.
This commit also improves the variable names, the comments and adds two `Debug()` lines.

Proto_OpenVPN.c: improve OvsProcessData(), fix out-of-bounds access found by Coverity

---

.ci/vpntools-check.sh
.cirrus.yml

- Perform `vpncmd /tools /cmd:check` after build
- Switch to 12.1-RELEASE and add 11.3-STABLE
- some tiny refinements
Closes #1048.

Refine FreeBSD CI

---

src/bin/hamcore/languages.txt
src/bin/hamcore/strtable_pt_br.stb

pt-br translation

---

README.md

While here, switch some links to https.

README: add installation for FreeBD etc

---

src/Cedar/IPC.c

src/Cedar/IPC.c: fix possible crash when using certificate authentication with OpenVPN

---

src/Cedar/Hub.c

- Bugfix: Imperfect Virtual Hub FDB lock may cause process crush.

src/Cedar/Hub.c: fix possible crash because of imperfect Virtual Hub FDB lock

---

AUTHORS.TXT
configure
src/BUILD_UNIX.md
src/BUILD_WINDOWS.md
src/WARNING.TXT

Some CMake options are added by myself (#1047 #1079). So I should
describe in document.
While here,
-  replace SoftEther project related http links with https 
- make configure script to respect environment CMAKE_FLAGS
- add myself to AUTHORS

Describe CMake options added by myself

---

src/Mayaqua/Network.c

Disable SSLv3

---

CMakeLists.txt
src/CMakeLists.txt
src/vpnbridge/CMakeLists.txt
src/vpnclient/CMakeLists.txt
src/vpncmd/CMakeLists.txt
src/vpnserver/CMakeLists.txt
systemd/softether-vpnbridge.service
systemd/softether-vpnclient.service
systemd/softether-vpnserver.service

Fix three issues when building RPM packages

---

src/Cedar/Proto.c

`ProtoHandleDatagrams()` takes care of deleting a session if marked as halted.
However, the check is performed when a packet for that session is received; that never happens if the remote host doesn't send at least a packet.
This commit fixes the issue by moving the check into the loop that iterates through all sessions.

Cedar/Proto.c: fix session deletion not being triggered in certain cases

---

src/bin/hamcore/strtable_cn.stb
src/bin/hamcore/strtable_en.stb
src/bin/hamcore/strtable_ja.stb
src/bin/hamcore/strtable_ko.stb
src/bin/hamcore/strtable_pt_br.stb
src/bin/hamcore/strtable_ru.stb
src/bin/hamcore/strtable_tw.stb

hamcore: correct mistake enable/disable in help meessages

---

src/Cedar/Cedar.h
src/Cedar/Client.c
src/Cedar/Client.h
src/Cedar/Command.c
src/Cedar/Command.h
src/Cedar/Connection.c
src/Cedar/Connection.h
src/Cedar/Link.c
src/Cedar/Protocol.c
src/Cedar/Session.c
src/Mayaqua/Encrypt.c
src/Mayaqua/Encrypt.h
src/bin/hamcore/strtable_cn.stb
src/bin/hamcore/strtable_en.stb
src/bin/hamcore/strtable_ja.stb
src/bin/hamcore/strtable_ko.stb
src/bin/hamcore/strtable_pt_br.stb
src/bin/hamcore/strtable_ru.stb
src/bin/hamcore/strtable_tw.stb

Openssl engine certificate authentication

---

src/Cedar/Command.c
src/Cedar/Server.c
src/Mayaqua/Network.c
src/Mayaqua/Network.h

Solves #1101 .
Currently it's only designed to pass the test. Preparing to add some commits.

Manage security level

---

src/Cedar/Command.c
src/Cedar/Server.c
src/Mayaqua/Network.c
src/Mayaqua/Network.h

Reverts SoftEtherVPN/SoftEtherVPN#1116

Revert "Manage security level"

---

src/Cedar/Server.c
src/Mayaqua/Network.c
src/Mayaqua/Network.h

Reverts SoftEtherVPN/SoftEtherVPN#1115

Revert "Add Tls_Disable1_3 (Import v4 change)"

---

src/Mayaqua/Unix.c

- Found the bad remove for lock files.

Found the bad remove for lock files.

---

.github/workflows/opensuse.yml

- basic OpenSUSE build workflow

add basic OpenSUSE workflow

---

src/bin/hamcore/strtable_ja.stb

It regressed to English in #1122.

Japanese: translate LH_AUTH_NG again

---

src/Mayaqua/Microsoft.c
src/Mayaqua/Microsoft.h
src/Mayaqua/Network.c

Also, reported unused variables are removed.

Mayaqua: Fix several warnings related to Windows data type mismatches

---

.gitmodules
CMakeLists.txt
src/CMakeLists.txt
src/hamcorebuilder/CMakeLists.txt
src/hamcorebuilder/FileSystem.c
src/hamcorebuilder/FileSystem.h
src/hamcorebuilder/main.c

https://github.com/SoftEtherVPN/libhamcore

hamcorebuilder: Use libhamcore to build archive

---

src/BUILD_UNIX.md

- update install dependencies (libsodium)
Since #1200 is now merged into master, `libsodium` is required for a successful build.  This PR addresses that.

Update BUILD_UNIX.md dependencies

---

CODE_OF_CONDUCT.md

Add (No) Code of Conduct

---

src/bin/hamcore/strtable_ru.stb

- Updated russian translation file
- 
-

Updated Russian translate

---

src/Mayaqua/DNS.c

```c
52 bytes in 2 blocks are definitely lost in loss record 5 of 13
at 0x483877F: malloc (vg_replace_malloc.c:307)
by 0x4ABB1BB: UnixMemoryAlloc (Unix.c:2033)
by 0x4A7FABF: InternalMalloc (Memory.c:3819)
by 0x4A7B769: MallocEx (Memory.c:3650)
by 0x4A7B769: Malloc (Memory.c:3641)
by 0x4AA71A9: CopyStr (Str.c:1884)
by 0x4A61A9C: DnsCacheReverseUpdate (DNS.c:257)
by 0x4A62123: DnsResolveReverse (DNS.c:506)
by 0x4A93EB3: GetHostName (Network.c:15023)
by 0x4A93EB3: AcceptInitEx (Network.c:12589)
by 0x4934659: TCPAcceptedThread (Listener.c:172)
by 0x4A76469: ThreadPoolProc (Kernel.c:872)
by 0x4ABD159: UnixDefaultThreadProc (Unix.c:1589)
by 0x51C2EA6: start_thread (pthread_create.c:477)
2,280 (684 direct, 1,596 indirect) bytes in 9 blocks are definitely lost in loss record 11 of 13
at …
```

Mayaqua/DNS.c: Fix memory leaks

---

src/Cedar/Proto_PPP.c

Currently EAP identifier starts from zero and causes duplication between the first packet (usually EAP Identity Request) and the second (usually EAP TLS Start).
This change uses unified identifier `NextId` which is already used by LCP and MSCHAPv2.
Moreover, EAP Success and Failure packets should use the same identifiers as Response so incorrect comments regarding hacks were removed.
Fixes https://github.com/SoftEtherVPN/SoftEtherVPN/issues/1350
- Fix EAP identifier duplication and use unified identifier with LCP and MSCHAPv2

Cedar/Proto_PPP: Fix EAP identifier duplication

---

src/bin/hamcore/strtable_ja.stb

hamcore(ja): just adding a missing ":"

---

.github/workflows/build_source_release.yml

as discussed in #1370 - result can be seen here https://github.com/rofl0r/SoftEtherVPN/releases/tag/9.99.0

add github workflow to create release tarball with submodules

---

.github/workflows/coverity.yml

thanks Paul Menzel for reporting this.
fixes #1372

add missing libsodium dependency to coverity pipeline

---

src/Cedar/Proto_PPP.c

Fixes: #1420 (Implement EAP-MSCHAPv2)
Sorry. 😢

Cedar/Proto_PPP.c: Fix memory leak in EAP-MSCHAPv2

---

src/Cedar/SW.c

as reported by @domosekai , installers built within PR pipeline are not able to uninstall. let us make them uninstallable as well

src/Cedar/SW.c: treat "0" build as legitimate

---

.cirrus.yml

CI: cirrus: drop LibreSSL builds

---

src/Mayaqua/Encrypt.c

Signed-off-by: Rosen Penev <rosenp@gmail.com>

fix compilation without OpenSSL engines

---

src/Mayaqua/CMakeLists.txt

-  add build time check for EVP_PKEY_get_raw_public_key() presense in OpenSSL lib

add build time check for EVP_PKEY_get_raw_public_key() presense in OpenSSL lib

---

CMakeLists.txt
systemd/softether-vpnserver.service

Reverts SoftEtherVPN/SoftEtherVPN#1402

Revert "RPM package and systemd service file fixes (for CentOS 8)"

---

.gitlab-ci.yml

cleaning up broken Ubuntu tasks.

CI: gitlab: remove broken tasks, leave only Illumos

---

src/bin/hamcore/openvpn_sample.ovpn

this works for OpenVPN-2.5 and higher.
I will check 2.4 and other implementations

add "data-ciphers" to generated OpenVPN configs

---

src/Cedar/Client.c
src/Cedar/Protocol.c
src/Mayaqua/Network.c

R-UDP bulk v2 introduced in #1039 is broken. This PR fixes it.

Fix UDP bulk v2 and protocol display

---

src/Mayaqua/Encrypt.c

As mentioned in #1578 , Openssl 3.0 deprecates old algorithm for PKCS12 and hence can't read old files created by Openssl 1.x unless explicitly loading the legacy provider. This PR loads it. 
This only affects reading and new p12 files are still created in new algorithm (readable by openssl 1.x).
Note: This PR has been edited to align with the stable build 9772 released today.

Fix PKCS12 import under OpenSSL 3.0

---

src/Cedar/IPC.c

Since PPP tunnel does not have link-layer addresses, IPv6 ND messages should not bear link-layer address options.
That means we should strip those options when relaying IPv6 ND to PPP layer and add back vice versa.
Before Windows 11, Windows built-in clients does not enforce the above requirement. 
But for some unknown reason, Windows 11 refuses to recognize IPv6 RA with source link-layer address option.
Therefore we need this fix.
I also added back source LL option to router solicitation sent from a client. This does not fix anything but saves the router from making unnecessary enquiries (-1 RTT).
Tested with Windows built-in L2TP and SSTP client, Android (VPN Client Pro) and iOS (SSTP Connect).
More testing is welcome.

Fix IPv6 ND for Windows 11 PPP clients

---

.github/ISSUE_TEMPLATE.md
README.md

Since many users are not aware / confused with the difference with Stable Edition, I think a feature by feature comparison on the main page can save lives.
My list is very likely incomplete. Inputs are welcome!

Add edition comparison to README.md

---

.appveyor.yml
.ci/azure-pipelines/linux.yml

fix ci build as OpenVPN now requires more deps

CI: install libcap-ng-dev as OpenVPN dependency

---

src/BUILD_WINDOWS.md

- Add instructions for dynamic linking OpenSSL for Windows users

Add build instruction for dynamic linking OpenSSL

---

src/Cedar/Proto_PPP.c

Cedar/Proto_PPP: Fix memory leak

---

src/Cedar/Proto_PPP.c

Fix thread safety after #1751

---

src/Cedar/Proto_PPP.c

Should fix #1760 and #1761.
Some of them were ignored as being just redundant checks (defensive programming, may help if code changes) or bogus (coverity apparently doesn't understand the SoftEther memtags).

Fixing up coverity report flags from #1760 and #1761

---

src/Cedar/Proto_PPP.c

Fix Radius authentication which is broken after #1751

Cedar/Proto_PPP: Fix radius authentication

---

.cirrus.yml

bump freebsd to 13.2, switch to openssl-3.1

CI: cirrus-ci: switch to freebsd-13.2

---

src/Mayaqua/Network.c

- add null check before SSL_CTX_set_ssl_version to avoid null-dereference.

fix potential crash.

---

src/bin/hamcore/strtable_ru.stb

- SE VPN-Client & Server GUI full translation 
- cmd part not translated

Big Russian language update

---

src/bin/hamcore/strtable_cn.stb
src/bin/hamcore/strtable_en.stb
src/bin/hamcore/strtable_ja.stb
src/bin/hamcore/strtable_ko.stb
src/bin/hamcore/strtable_ru.stb
src/bin/hamcore/strtable_tw.stb

- Fixed comments about the VpnAzureSetEable command in strtable file.

fixed comments in strtable file 

---

src/Mayaqua/Network.c

- I sent new pull request on illegal access. 
- 
-

Bind outgoing connection to a specific IP address (avoid illegal access)

---

src/bin/hamcore/strtable_pt_br.stb

- Fix missing argument name in strtable file

Fix missing argument name in strtable file

---

src/Mayaqua/Network.c

partially merge https://github.com/SoftEtherVPN/SoftEtherVPN/pull/1921
@icy17  ?

fix nullptr deref

---

src/Mayaqua/pkcs11f.h
src/Mayaqua/pkcs11t.h

gcc14 is not happy on "error: passing argument .. from incompatible pointer type [-Wincompatible-pointer-types]"

adjust types of variables found by gcc14

---

src/Cedar/Proto_L2TP.c

Should fix #2043 
Now there may be another reason for it being stuck elsewhere, but I just did the thing which should had been done a long time ago, my bad

Incorrect variable used while iterating through sessions which makes the loop stuck

---

.github/workflows/docker-vpnbridge.yml
.github/workflows/docker-vpnclient.yml
.github/workflows/docker-vpnserver.yml
Dockerfile
docker-compose.vpnclient.yaml
docker-compose.yaml

@weidi  can you please review ?

CI: move docker build machinery to the main repo

---

.github/workflows/docker-aio.yml

Docker ci followup

---

.github/workflows/docker-aio.yml

CI: docker: fix tags

---

src/bin/hamcore/strtable_id.stb

- rephrase Indonesian translation that causing stbchecker fail

Fix Indonesian translation with printf formatting
